"""
Seed batch 3 — fills thin categories to 8-10 tools each.
Covers: writing-ai, research-ai, design-ai, document-ai,
        productivity-ai, music-generation, translation-ai, ai-agents

Idempotent — uses tool ID as Firestore document ID.

Usage:
    cd backend
    python -m scripts.seed_tools_batch3
"""

import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.db.firestore_client import get_db

TODAY = datetime.date.today().isoformat()


def ftd(credits=None, gen_limit=None, daily=None, monthly=None, watermark=False,
        watermark_details=None, features=None, api=None, commercial=True):
    return {
        "credits": credits, "generation_limit": gen_limit,
        "daily_limit": daily, "monthly_limit": monthly,
        "has_watermark": watermark, "watermark_details": watermark_details,
        "feature_restrictions": features, "api_restrictions": api,
        "commercial_use_allowed": commercial,
    }


TOOLS = [

    # ── WRITING AI (was 6, target 9) ─────────────────────────────

    {
        "id": "wordtune",
        "name": "Wordtune",
        "description": "AI writing assistant that rewrites and rephrases existing text in multiple tones and styles. Strong for non-native English speakers and professionals who need clearer communication.",
        "category_id": "writing-ai",
        "website_url": "https://www.wordtune.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="10 rewrites and AI suggestions per day on free plan",
            features="Free: 10 rewrites/day, 3 document summaries/month, unlimited spelling/grammar; Advanced $4.89/month annual",
            api="No public API",
        ),
        "capabilities": ["text rewriting", "paraphrasing", "tone adjustment", "sentence shortening", "sentence expansion", "AI summarisation", "grammar correction"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["improving clarity of existing writing", "rephrasing for different tones", "non-native English writing", "email and report refinement"],
        "limitations": ["10 rewrites/day on free", "rewrites only — not generative", "works on existing text not a blank page"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "hemingway-editor",
        "name": "Hemingway Editor",
        "description": "Writing clarity tool that highlights complex sentences, passive voice, adverbs, and readability issues. The web version is completely free with no account required.",
        "category_id": "writing-ai",
        "website_url": "https://hemingwayapp.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited use on web browser — fully free",
            features="Web app fully free; Desktop app one-time $19.99; AI rewrite feature requires paid subscription",
            api="No public API",
        ),
        "capabilities": ["readability scoring", "passive voice detection", "adverb highlighting", "complex sentence detection", "grade level analysis"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["improving writing clarity", "academic writing", "blog posts", "content editing", "reducing complex sentences"],
        "limitations": ["editing tool only — not generative AI", "AI rewrite requires paid subscription", "no API access"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "gamma-app",
        "name": "Gamma",
        "description": "AI presentation and document builder that creates polished slide decks, documents, and web pages from a text prompt in seconds. Minimal effort, professional output.",
        "category_id": "writing-ai",
        "website_url": "https://gamma.app",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            credits="400 AI credits on signup (one-time, does not refill on free plan)",
            features="Free: 400 starter credits one-time; Plus $8/month annual: 400 credits/month; Pro $18/month: 1,000 credits/month",
            api="No public API",
        ),
        "capabilities": ["AI presentation generation", "document creation", "web page creation", "slide design", "template customisation", "image generation"],
        "input_types": ["text"],
        "output_types": ["document", "image"],
        "watermark_info": "Gamma branding on free exports",
        "api_available": False,
        "best_use_cases": ["pitch decks", "business presentations", "reports", "landing pages", "educational materials"],
        "limitations": ["400 credits one-time on free (not monthly)", "Gamma branding on free exports", "no API access"],
        "verified_date": TODAY, "active": True,
    },

    # ── RESEARCH AI (was 5, target 8) ─────────────────────────────

    {
        "id": "research-rabbit",
        "name": "ResearchRabbit",
        "description": "Free literature discovery and citation mapping tool. Visualises connections between academic papers through interactive networks — helps researchers find related work they would otherwise miss.",
        "category_id": "research-ai",
        "website_url": "https://www.researchrabbit.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Core features completely free; premium plan announced for advanced AI features",
            features="Free: unlimited paper collections, citation mapping, author tracking, collaboration; Premium tier coming",
            api="No public API",
        ),
        "capabilities": ["citation mapping", "paper discovery", "literature network visualisation", "author tracking", "collection management", "related paper recommendations"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["academic literature review", "finding related papers", "mapping research fields", "systematic reviews", "tracking author output"],
        "limitations": ["covers published academic papers only", "premium tier coming with advanced AI", "no document upload"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "semantic-scholar",
        "name": "Semantic Scholar",
        "description": "Free AI-powered academic search engine from the Allen Institute for AI. Covers 220M+ papers with semantic search, AI-generated TLDR summaries, citation analysis, and paper recommendations.",
        "category_id": "research-ai",
        "website_url": "https://www.semanticscholar.org",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Fully free — no account required for search",
            api="API free tier: 100 requests per 5 minutes; higher limits available on request",
        ),
        "capabilities": ["academic paper search", "AI TLDR summaries", "citation analysis", "semantic search", "paper recommendations", "author profiles", "research feeds"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["academic research", "finding papers on specific topics", "citation analysis", "literature discovery", "staying current in a field"],
        "limitations": ["academic papers only", "TLDR quality varies", "no document upload or Q&A on your own files"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "connected-papers",
        "name": "Connected Papers",
        "description": "Visual tool for exploring academic papers related to a given work. Creates a graph based on co-citation and bibliographic coupling — helps find relevant prior and derivative work in a research field.",
        "category_id": "research-ai",
        "website_url": "https://www.connectedpapers.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="5 free graphs per month on free plan",
            features="Free: 5 graphs/month; Academic $3/month: unlimited graphs",
            api="No public API",
        ),
        "capabilities": ["paper relationship visualisation", "citation network mapping", "prior work discovery", "derivative work discovery", "literature gap identification"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["finding related papers", "literature review scoping", "understanding a research field", "identifying seminal works", "finding derivative studies"],
        "limitations": ["5 graphs/month on free", "academic papers only", "can be slow for niche topics"],
        "verified_date": TODAY, "active": True,
    },

    # ── DESIGN AI (was 5, target 8) ───────────────────────────────

    {
        "id": "framer-ai",
        "name": "Framer AI",
        "description": "AI-powered website builder that generates full production-ready websites from a text prompt. Also functions as a professional no-code design tool with animations and CMS.",
        "category_id": "design-ai",
        "website_url": "https://www.framer.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free plan: design and preview only — no publishing to live domain; Basic $10/month annual to go live",
            api="CMS REST API on paid plans",
            commercial=True,
        ),
        "capabilities": ["AI website generation", "no-code web design", "responsive layouts", "animation", "CMS", "prototype creation", "component design"],
        "input_types": ["text", "image"],
        "output_types": ["prototype", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["portfolio websites", "landing pages", "startup websites", "rapid prototyping", "design system creation"],
        "limitations": ["free plan cannot publish to live domain", "Basic $10/month to go live", "AI generation uses credits"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "adobe-express",
        "name": "Adobe Express",
        "description": "Adobe's free AI-powered design tool for social media posts, videos, PDFs, and marketing materials. Includes Adobe Stock assets and Firefly-powered generative AI features.",
        "category_id": "design-ai",
        "website_url": "https://www.adobe.com/express",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: core templates, limited assets, basic AI; Premium $9.99/month: 250 Firefly generative credits, brand kits, 100GB storage",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["social media design", "video creation", "PDF creation", "AI image generation", "background removal", "template customisation", "brand kits"],
        "input_types": ["text", "image"],
        "output_types": ["image", "document"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["social media graphics", "marketing materials", "quick videos", "flyers and posters", "business documents"],
        "limitations": ["limited generative AI credits on free", "advanced brand features require Premium", "less powerful than full Creative Cloud"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "recraft",
        "name": "Recraft",
        "description": "AI image and vector generation tool specialising in brand-consistent design assets. Unique for generating SVG vectors and icons in a consistent style — strong for product and UI design.",
        "category_id": "design-ai",
        "website_url": "https://www.recraft.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="50 free image generations per month",
            features="Free: 50 generations/month, public outputs; Pro $12/month: 1,000 generations, private outputs",
            api="API available on paid plans",
            commercial=True,
        ),
        "capabilities": ["AI image generation", "vector SVG generation", "icon generation", "illustration creation", "brand style consistency", "image editing"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["brand illustration systems", "icon sets", "product UI assets", "consistent style generation", "vector art creation"],
        "limitations": ["50 free generations/month", "free outputs are public", "SVG quality varies by complexity"],
        "verified_date": TODAY, "active": True,
    },

    # ── DOCUMENT AI (was 5, target 8) ─────────────────────────────

    {
        "id": "mathpix",
        "name": "Mathpix",
        "description": "AI tool that converts handwritten and printed math, chemistry, and scientific notation into LaTeX, MathML, or digital text. Essential for researchers and students working with equations.",
        "category_id": "document-ai",
        "website_url": "https://mathpix.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="20 free equation snips per month",
            features="Free: 20 snips/month; Pro $4.99/month: 5,000 snips/month; API free tier: 1,000 calls/month",
            api="API free tier: 1,000 calls/month",
        ),
        "capabilities": ["handwritten math recognition", "equation to LaTeX", "PDF scientific conversion", "chemistry notation recognition", "table extraction"],
        "input_types": ["image", "document"],
        "output_types": ["text", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["converting handwritten equations", "digitising scientific papers", "LaTeX generation", "chemistry formula recognition", "academic document processing"],
        "limitations": ["20 free snips/month", "specialised for STEM content", "complex diagrams may need manual correction"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "pdf-ai",
        "name": "PDF.ai",
        "description": "Chat with any PDF — ask questions, get summaries, extract data. Supports large documents with a simple focused interface. One of the easiest PDF Q&A tools to get started with.",
        "category_id": "document-ai",
        "website_url": "https://pdf.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="1 PDF per day, up to 120 pages, 10MB on free plan",
            features="Free: 1 PDF/day, 120 pages, 10MB max; Starter $12/month: 50 PDFs/day",
            api="No public API",
        ),
        "capabilities": ["PDF Q&A", "document summarisation", "data extraction", "citation generation", "multi-document support"],
        "input_types": ["document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["research paper Q&A", "legal document review", "contract analysis", "textbook study", "report summarisation"],
        "limitations": ["1 PDF/day on free", "120 page limit on free", "no API access"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "descript",
        "name": "Descript",
        "description": "AI-powered audio and video editor using text-based editing — edit media by editing the transcript. Includes filler-word removal, Studio Sound noise cleanup, Overdub voice cloning, and screen recording.",
        "category_id": "document-ai",
        "website_url": "https://www.descript.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="60 minutes of media per month on free plan",
            features="Free: 60 min/month, 100 AI credits one-time, 720p exports with watermark; Hobbyist $16/month annual: no watermark",
            watermark=True,
            watermark_details="Free plan exports capped at 720p with Descript watermark",
            api="No public API",
            commercial=False,
        ),
        "capabilities": ["text-based video editing", "audio editing", "transcription", "filler word removal", "noise removal", "voice cloning", "screen recording", "podcast editing"],
        "input_types": ["audio", "video"],
        "output_types": ["audio", "video", "text"],
        "watermark_info": "Free plan exports include watermark at 720p max",
        "api_available": False,
        "best_use_cases": ["podcast production", "YouTube video editing", "interview editing", "screen recording with captions", "corporate video creation"],
        "limitations": ["60 min/month free", "watermark on free exports", "voice cloning needs good audio samples"],
        "verified_date": TODAY, "active": True,
    },

    # ── PRODUCTIVITY AI (was 5, target 8) ─────────────────────────

    {
        "id": "make",
        "name": "Make (formerly Integromat)",
        "description": "Visual automation platform for connecting apps and building complex multi-step workflows without code. More powerful than Zapier for complex automations. 3,000+ app integrations.",
        "category_id": "productivity-ai",
        "website_url": "https://www.make.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="1,000 operations per month on free plan",
            features="Free: 1,000 ops/month, 2 active scenarios, 15-min minimum interval; Core $9/month annual: 10,000 ops",
            api="Full API access on all plans",
            commercial=True,
        ),
        "capabilities": ["visual workflow automation", "3,000+ app integrations", "multi-step automation", "data transformation", "webhook support", "scheduling", "AI integrations"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["business process automation", "marketing workflows", "data pipeline creation", "CRM automation", "complex multi-step integrations"],
        "limitations": ["1,000 ops/month on free", "only 2 active scenarios on free", "15-min minimum polling on free"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "mem-ai",
        "name": "Mem",
        "description": "AI-first note-taking app that automatically organises notes and surfaces relevant information. Uses AI to find connections between notes, draft content, and answer questions from your knowledge base.",
        "category_id": "productivity-ai",
        "website_url": "https://mem.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: core note-taking with basic AI; Pro $14.99/month: unlimited AI features, smart search, AI drafting",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["AI note-taking", "automatic organisation", "knowledge base Q&A", "smart search", "AI drafting", "connection discovery between notes"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["personal knowledge management", "meeting notes", "research organisation", "writing from your own notes", "team knowledge base"],
        "limitations": ["free AI features limited", "full AI requires Pro $14.99/month", "web and mobile only"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "todoist-ai",
        "name": "Todoist AI Assistant",
        "description": "Todoist's built-in AI assistant breaks down tasks, estimates effort, and suggests sub-tasks automatically. Integrated into one of the most popular task management apps.",
        "category_id": "productivity-ai",
        "website_url": "https://todoist.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: 5 active projects, basic AI suggestions; Pro $4/month annual: unlimited projects, full AI assistant, reminders",
            api="REST API on all plans",
            commercial=True,
        ),
        "capabilities": ["AI task breakdown", "effort estimation", "sub-task suggestions", "natural language task entry", "project planning", "team collaboration"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["personal task management", "project planning", "team task coordination", "daily planning with AI", "GTD workflow"],
        "limitations": ["5 active projects on free", "AI features limited on free", "Pro $4/month for full AI assistant"],
        "verified_date": TODAY, "active": True,
    },

    # ── MUSIC GENERATION (was 4, target 7) ────────────────────────

    {
        "id": "boomy",
        "name": "Boomy",
        "description": "AI music creation platform that generates original songs in seconds and lets you release them to Spotify and other streaming platforms. One of the easiest ways to create and publish AI-generated music.",
        "category_id": "music-generation",
        "website_url": "https://boomy.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited song creation on free plan",
            features="Free: unlimited creation, save 25 tracks, release 1 project (up to 3 songs), no commercial use; Creator $9.99/month: 500 saves, commercial rights, MP3 downloads",
            commercial=False,
        ),
        "capabilities": ["AI song generation", "music style selection", "streaming platform release", "song customisation", "lyric assistance"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["quick music creation", "releasing to streaming platforms", "background music", "hobbyist music production", "social media content"],
        "limitations": ["save limit of 25 tracks on free", "no commercial use on free", "limited control over musical structure", "MP3 downloads require paid"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "aiva",
        "name": "AIVA",
        "description": "AI music composer that creates original scores in classical, cinematic, and modern styles. Registered composer with SACEM. Used by game developers, filmmakers, and advertisers for custom soundtracks.",
        "category_id": "music-generation",
        "website_url": "https://www.aiva.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="3 MP3 downloads per month on free plan",
            features="Free: unlimited track creation, 3 downloads/month (MP3 only), non-commercial use; Standard $15/month: unlimited downloads, commercial rights",
            commercial=False,
        ),
        "capabilities": ["AI composition", "orchestral music generation", "cinematic scoring", "style presets", "MIDI export", "stem download", "emotion-based generation"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["film scoring", "game soundtracks", "commercial music", "classical composition", "background music for media"],
        "limitations": ["3 downloads/month on free", "no commercial use on free", "less suited for pop/electronic vs classical"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "loudly",
        "name": "Loudly",
        "description": "AI music generator focused on background and production music. Creates royalty-free tracks by mood, genre, and tempo. Includes an API for developers building apps with dynamic soundtracks.",
        "category_id": "music-generation",
        "website_url": "https://www.loudly.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="10 free song generations per month",
            features="Free: 10 generations/month, limited downloads, non-commercial; Pro $7.99/month: 100 generations, commercial licence",
            commercial=False,
        ),
        "capabilities": ["AI music generation", "mood-based generation", "genre selection", "stem separation", "royalty-free tracks", "tempo control"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["video background music", "podcast intros", "content creation", "game audio", "royalty-free music library"],
        "limitations": ["10 free generations/month", "no commercial use on free", "less creative than Suno for full songs with lyrics"],
        "verified_date": TODAY, "active": True,
    },

    # ── TRANSLATION AI (was 4, target 7) ──────────────────────────

    {
        "id": "deepl-write",
        "name": "DeepL Write",
        "description": "AI writing improvement tool from DeepL. Improves phrasing, grammar, and style in English and German text. Different from DeepL Translate — focuses on improving what you write, not translating it.",
        "category_id": "translation-ai",
        "website_url": "https://www.deepl.com/write",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: basic writing improvements, limited text length; Pro included with DeepL Pro subscription",
            api="No separate public API",
            commercial=True,
        ),
        "capabilities": ["text improvement", "grammar correction", "style suggestions", "tone adjustment", "rephrasing", "English and German support"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["professional writing polish", "business email refinement", "academic writing", "non-native English/German writing"],
        "limitations": ["English and German only", "writing assistant — not a translator", "full features need DeepL Pro"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "modernmt",
        "name": "ModernMT",
        "description": "Adaptive machine translation API that learns from human corrections over time. Context-aware translation that improves with feedback. Used by professional translators and localisation agencies.",
        "category_id": "translation-ai",
        "website_url": "https://www.modernmt.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="200,000 characters per month on free API tier",
            features="Free API: 200k chars/month; pay-as-you-go after free quota",
            api="REST API — 200k chars/month free",
            commercial=True,
        ),
        "capabilities": ["adaptive machine translation", "context-aware translation", "learning from corrections", "50+ language pairs", "glossary support", "batch translation"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["professional translation workflows", "CAT tool integration", "adaptive enterprise translation", "localisation with correction learning"],
        "limitations": ["API-focused with no clean web UI", "adaptive features require human correction data", "best for professional translator workflows"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "argos-translate",
        "name": "Argos Translate",
        "description": "Open-source offline machine translation that runs entirely locally — no internet required, no data sent to servers. Privacy-first alternative to cloud translation supporting 30+ language pairs.",
        "category_id": "translation-ai",
        "website_url": "https://www.argosopentech.com",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited — runs fully offline with no usage limits",
            features="Completely free open source; requires local installation; Python library or desktop app",
            api="Python library for local integration",
            commercial=True,
        ),
        "capabilities": ["offline translation", "30+ language pairs", "privacy-preserving translation", "batch translation", "Python integration", "no internet required"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["privacy-sensitive translation", "offline environments", "regulated industries", "open-source projects", "developer local translation"],
        "limitations": ["lower quality than DeepL/Google for nuanced text", "requires local installation", "no web UI by default"],
        "verified_date": TODAY, "active": True,
    },

    # ── AI AGENTS (was 7, target 10) ──────────────────────────────

    {
        "id": "agentgpt",
        "name": "AgentGPT",
        "description": "Browser-based autonomous AI agent that plans and executes multi-step tasks without any local installation. Runs agent chains directly in your browser — open source and self-hostable.",
        "category_id": "ai-agents",
        "website_url": "https://agentgpt.reworkd.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: limited agent runs per day; Pro $40/month: unlimited runs, GPT-4, custom model selection",
            api="Open source — self-hostable",
            commercial=True,
        ),
        "capabilities": ["autonomous task execution", "multi-step planning", "web browsing", "code execution", "browser-based agents", "open source"],
        "input_types": ["text"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["automated research", "no-install agent prototyping", "task chaining", "open-source agent experimentation"],
        "limitations": ["limited free runs per day", "less stable than local frameworks", "Pro $40/month for production use"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "activepieces",
        "name": "Activepieces",
        "description": "Open-source no-code automation platform and Zapier alternative. Self-hostable for complete data privacy. Supports 200+ integrations and AI agent flows. Free cloud tier available.",
        "category_id": "ai-agents",
        "website_url": "https://www.activepieces.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="1,000 tasks/month on cloud free plan",
            features="Free cloud: 1,000 tasks/month, 5 active flows; Self-hosted: completely unlimited and free",
            api="Full REST API",
            commercial=True,
        ),
        "capabilities": ["no-code automation", "200+ integrations", "AI agent flows", "webhook support", "self-hosting", "open source", "data transformation"],
        "input_types": ["text", "code"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["privacy-first automation", "self-hosted workflows", "Zapier alternative", "business process automation", "AI-powered workflows"],
        "limitations": ["1,000 tasks/month on cloud free", "self-hosting requires technical setup", "smaller integration library than Zapier"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "flowise",
        "name": "Flowise",
        "description": "Open-source visual tool for building LLM-powered apps and AI agent flows using drag-and-drop. Built on LangChain. Completely free when self-hosted — great for building RAG chatbots and agent pipelines.",
        "category_id": "ai-agents",
        "website_url": "https://flowiseai.com",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited on self-hosted deployment",
            features="Fully free open source when self-hosted; Flowise Cloud available for managed hosting",
            api="REST API and embedded chat widget",
            commercial=True,
        ),
        "capabilities": ["visual LLM app builder", "AI agent creation", "RAG pipeline building", "chatbot creation", "tool integration", "drag-and-drop workflow", "LangChain-based"],
        "input_types": ["text", "code", "document"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["building RAG chatbots", "visual AI workflow creation", "LLM app prototyping", "customer support bots", "internal knowledge assistants"],
        "limitations": ["requires technical setup for self-hosting", "needs own LLM API keys", "rapidly evolving codebase"],
        "verified_date": TODAY, "active": True,
    },
]


def seed():
    db = get_db()
    col = db.collection("tools")
    seeded = 0
    for tool in TOOLS:
        col.document(tool["id"]).set(tool)
        print(f"  \u2713 {tool['name']} ({tool['category_id']}) \u2014 {tool['pricing_type']}")
        seeded += 1
    print(f"\nSeeded {seeded} new tools across thin categories.")


if __name__ == "__main__":
    seed()
