"""
Seed script: writes sample AI tool records to Firestore.
Idempotent — uses a fixed tool ID as the document ID.

Usage (from repo root, with backend .env configured):
    cd backend
    python -m scripts.seed_tools
"""

import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.db.firestore_client import get_db

TODAY = datetime.date.today().isoformat()

TOOLS = [
    {
        "id": "chatgpt",
        "name": "ChatGPT",
        "description": "OpenAI's conversational AI assistant capable of answering questions, writing, coding, and reasoning across a wide range of topics.",
        "category_id": "chat-ai",
        "website_url": "https://chat.openai.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": None,
            "daily_limit": "Limited messages on GPT-4o in free tier",
            "monthly_limit": None,
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "GPT-4o access limited; no image generation in free tier",
            "api_restrictions": "API requires paid plan",
            "commercial_use_allowed": True,
        },
        "capabilities": ["text generation", "question answering", "code generation", "summarisation", "translation"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["writing assistance", "coding help", "research", "brainstorming", "customer support"],
        "limitations": ["knowledge cutoff", "can hallucinate facts", "free tier has usage limits"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "claude",
        "name": "Claude",
        "description": "Anthropic's AI assistant focused on safety, helpfulness, and honest responses. Strong at long-document analysis and nuanced reasoning.",
        "category_id": "chat-ai",
        "website_url": "https://claude.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": None,
            "daily_limit": "Limited messages per day on free tier",
            "monthly_limit": None,
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Claude 3.5 Sonnet limited on free; no API access",
            "api_restrictions": "API requires paid plan",
            "commercial_use_allowed": True,
        },
        "capabilities": ["text generation", "long document analysis", "question answering", "code generation", "summarisation"],
        "input_types": ["text", "document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["document analysis", "long-form writing", "nuanced reasoning", "research", "coding"],
        "limitations": ["knowledge cutoff", "no image generation", "free tier message limits"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "midjourney",
        "name": "Midjourney",
        "description": "A leading AI image generation tool that creates high-quality artistic images from text prompts via a Discord bot or web interface.",
        "category_id": "image-generation",
        "website_url": "https://www.midjourney.com",
        "pricing_type": "Paid Only",
        "free_availability": False,
        "free_tier_details": None,
        "capabilities": ["image generation", "image variation", "upscaling", "style transfer"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["artistic image creation", "concept art", "marketing visuals", "creative exploration"],
        "limitations": ["no free tier", "no public API", "requires Discord or web account", "commercial use requires higher tier"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "stable-diffusion-xl",
        "name": "Stable Diffusion XL",
        "description": "Open-source text-to-image model by Stability AI. Can be run locally for free or used via hosted APIs.",
        "category_id": "image-generation",
        "website_url": "https://stability.ai/stable-image",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": "Unlimited when self-hosted",
            "daily_limit": None,
            "monthly_limit": None,
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Requires local GPU for self-hosting",
            "api_restrictions": None,
            "commercial_use_allowed": True,
        },
        "capabilities": ["image generation", "inpainting", "outpainting", "image-to-image"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["open-source image generation", "local deployment", "commercial projects", "fine-tuning"],
        "limitations": ["requires powerful GPU for local use", "setup complexity for self-hosting"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "github-copilot",
        "name": "GitHub Copilot",
        "description": "AI-powered code completion and chat assistant integrated directly into popular code editors like VS Code.",
        "category_id": "coding-ai",
        "website_url": "https://github.com/features/copilot",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": "2000 completions and 50 chat messages per month on free tier",
            "daily_limit": None,
            "monthly_limit": "2000 completions / 50 chat messages",
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Free tier has monthly limits; advanced models on paid",
            "api_restrictions": None,
            "commercial_use_allowed": True,
        },
        "capabilities": ["code completion", "code generation", "code explanation", "code review", "chat"],
        "input_types": ["code", "text"],
        "output_types": ["code", "text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["IDE code completion", "generating boilerplate", "explaining unfamiliar code", "test generation"],
        "limitations": ["requires GitHub account", "free tier has monthly limits", "may suggest insecure code"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "cursor",
        "name": "Cursor",
        "description": "AI-first code editor (VS Code fork) with deep AI integration for code generation, editing, and chat across your entire codebase.",
        "category_id": "coding-ai",
        "website_url": "https://cursor.sh",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": "2-week free trial of Pro; then free tier with limited requests",
            "daily_limit": None,
            "monthly_limit": "Limited fast requests on free tier",
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Free tier has limited fast AI requests per month",
            "api_restrictions": None,
            "commercial_use_allowed": True,
        },
        "capabilities": ["code generation", "codebase chat", "code editing", "bug fixing", "code explanation"],
        "input_types": ["code", "text"],
        "output_types": ["code", "text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["full-codebase AI editing", "refactoring", "feature development", "debugging"],
        "limitations": ["free tier limited requests", "large codebases may hit context limits"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "elevenlabs",
        "name": "ElevenLabs",
        "description": "AI voice synthesis platform with highly realistic text-to-speech and voice cloning capabilities.",
        "category_id": "voice-audio",
        "website_url": "https://elevenlabs.io",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": "10,000 characters per month",
            "generation_limit": None,
            "daily_limit": None,
            "monthly_limit": "10,000 characters",
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Limited to 3 custom voices; lower quality downloads on free tier",
            "api_restrictions": "API available on free tier with limits",
            "commercial_use_allowed": False,
        },
        "capabilities": ["text-to-speech", "voice cloning", "voice design", "speech-to-speech"],
        "input_types": ["text", "audio"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["voiceovers", "audiobook narration", "podcast production", "content creation", "accessibility"],
        "limitations": ["free tier: 10k chars/month, no commercial use", "voice cloning quality varies"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "suno",
        "name": "Suno",
        "description": "AI music generation platform that creates full songs with vocals and instrumentation from text prompts.",
        "category_id": "music-generation",
        "website_url": "https://suno.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": "50 credits per day (\u224810 songs)",
            "generation_limit": "~10 songs per day",
            "daily_limit": "50 credits",
            "monthly_limit": None,
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Free tier songs cannot be used commercially",
            "api_restrictions": "No public API",
            "commercial_use_allowed": False,
        },
        "capabilities": ["music generation", "song creation", "lyric generation", "instrumental generation"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["creating background music", "song demos", "creative exploration", "content soundtracks"],
        "limitations": ["free tier: no commercial use", "limited control over musical structure", "no public API"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "notion-ai",
        "name": "Notion AI",
        "description": "AI writing and productivity assistant built into Notion, helping users draft, summarise, and organise content within their workspace.",
        "category_id": "productivity-ai",
        "website_url": "https://www.notion.com/product/ai",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": {
            "credits": "20 free AI responses trial",
            "generation_limit": "20 AI actions then paid add-on required",
            "daily_limit": None,
            "monthly_limit": None,
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "AI requires add-on after trial; Notion workspace itself has free tier",
            "api_restrictions": None,
            "commercial_use_allowed": True,
        },
        "capabilities": ["writing assistance", "summarisation", "action item extraction", "translation", "brainstorming"],
        "input_types": ["text", "document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["meeting notes summarisation", "document drafting", "knowledge base management", "task extraction"],
        "limitations": ["requires Notion workspace", "AI is a paid add-on after trial", "not a standalone tool"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "perplexity",
        "name": "Perplexity AI",
        "description": "AI-powered search engine that provides direct answers to questions with cited sources, combining search and language model capabilities.",
        "category_id": "research-ai",
        "website_url": "https://www.perplexity.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": None,
            "daily_limit": "Limited Pro searches per day on free tier",
            "monthly_limit": None,
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Free tier uses standard model; Pro searches limited",
            "api_restrictions": "API requires paid plan",
            "commercial_use_allowed": True,
        },
        "capabilities": ["web search", "question answering", "source citation", "research synthesis", "follow-up questions"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["research", "fact checking", "current events", "quick answers with sources", "academic research"],
        "limitations": ["free tier limited Pro searches", "answers can still hallucinate despite citations"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "runway-ml",
        "name": "Runway",
        "description": "Professional AI video generation and editing platform used by filmmakers and creators for text-to-video, image-to-video, and video editing.",
        "category_id": "video-generation",
        "website_url": "https://runwayml.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": "125 credits free on signup",
            "generation_limit": "Limited generations from free credits",
            "daily_limit": None,
            "monthly_limit": None,
            "has_watermark": True,
            "watermark_details": "Free tier videos include Runway watermark",
            "feature_restrictions": "Limited resolution and duration on free tier",
            "api_restrictions": "API requires paid plan",
            "commercial_use_allowed": False,
        },
        "capabilities": ["text-to-video", "image-to-video", "video editing", "background removal", "motion tracking"],
        "input_types": ["text", "image", "video"],
        "output_types": ["video"],
        "watermark_info": "Free tier adds Runway watermark to generated videos",
        "api_available": True,
        "best_use_cases": ["short film production", "marketing videos", "social media content", "creative video generation"],
        "limitations": ["free tier: watermark, limited credits, no commercial use", "high-quality output requires paid plan"],
        "verified_date": TODAY,
        "active": True,
    },
    {
        "id": "deepl",
        "name": "DeepL",
        "description": "High-accuracy AI translation service supporting 30+ languages, known for natural-sounding translations surpassing many competitors.",
        "category_id": "translation-ai",
        "website_url": "https://www.deepl.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": {
            "credits": None,
            "generation_limit": None,
            "daily_limit": None,
            "monthly_limit": "500,000 characters per month via API free tier",
            "has_watermark": False,
            "watermark_details": None,
            "feature_restrictions": "Free web translator has no document limit but API is capped",
            "api_restrictions": "API free tier: 500,000 chars/month",
            "commercial_use_allowed": True,
        },
        "capabilities": ["text translation", "document translation", "glossary support", "formality control"],
        "input_types": ["text", "document"],
        "output_types": ["text", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["professional document translation", "multilingual content", "website localisation", "business communication"],
        "limitations": ["30+ languages (fewer than Google Translate)", "API free tier character limit"],
        "verified_date": TODAY,
        "active": True,
    },
]


def seed():
    db = get_db()
    col = db.collection("tools")
    for tool in TOOLS:
        doc_id = tool["id"]
        col.document(doc_id).set(tool)
        print(f"  \u2713 {tool['name']} ({tool['pricing_type']})")
    print(f"\nSeeded {len(TOOLS)} tools.")


if __name__ == "__main__":
    seed()
