"""
Additional AI tools seed — adds 40+ new tools across all 13 categories.
Idempotent — uses tool ID as document ID.

Usage:
    cd backend
    python -m scripts.seed_tools_new
"""

import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.db.firestore_client import get_db

TODAY = datetime.date.today().isoformat()

def ftd(credits=None, gen_limit=None, daily=None, monthly=None, watermark=False,
        watermark_details=None, features=None, api=None, commercial=True):
    return {
        "credits": credits, "generation_limit": gen_limit,
        "daily_limit": daily, "monthly_limit": monthly,
        "has_watermark": watermark, "watermark_details": watermark_details,
        "feature_restrictions": features, "api_restrictions": api,
        "commercial_use_allowed": commercial,
    }

NEW_TOOLS = [

    # ── CHAT & CONVERSATIONAL AI ─────────────────────────────────────────────

    {
        "id": "grok",
        "name": "Grok",
        "description": "xAI's conversational AI assistant with real-time web access and integration with X (formerly Twitter). Known for directness, humor, and reasoning capabilities.",
        "category_id": "chat-ai",
        "website_url": "https://grok.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="Limited messages on free tier",
            features="Grok 3 limited on free; SuperGrok at $30/month for higher limits",
            api="API requires paid plan; free $150 credit expired May 2025",
        ),
        "capabilities": ["text generation", "real-time web search", "code generation", "image understanding", "reasoning", "image generation"],
        "input_types": ["text", "image"],
        "output_types": ["text", "image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["real-time news analysis", "X/Twitter content", "coding", "research", "uncensored Q&A"],
        "limitations": ["free tier message limits", "SuperGrok required for full access", "X account needed for some features"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "microsoft-copilot",
        "name": "Microsoft Copilot",
        "description": "Microsoft's AI assistant powered by GPT-4 and integrated across Windows, Edge, Bing, and Microsoft 365. Free with generous daily limits.",
        "category_id": "chat-ai",
        "website_url": "https://copilot.microsoft.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="Generous daily message limit on free tier",
            features="Copilot Pro ($20/month) adds Microsoft 365 integration and priority access",
            api="API via Azure OpenAI Service",
        ),
        "capabilities": ["text generation", "web search", "image generation", "document analysis", "code generation", "translation"],
        "input_types": ["text", "image", "document"],
        "output_types": ["text", "image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["Microsoft 365 productivity", "web research", "Windows integration", "image generation", "document summarisation"],
        "limitations": ["best value with Microsoft 365 subscription", "free tier daily limits", "integration depth requires paid"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "le-chat",
        "name": "Le Chat (Mistral AI)",
        "description": "Mistral AI's conversational assistant powered by their frontier models. Fast, multilingual, and strong at reasoning and coding.",
        "category_id": "chat-ai",
        "website_url": "https://chat.mistral.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free access to Mistral Small and Medium models; Pro at €14.99/month for frontier models",
            api="API separate; free tier available with rate limits",
        ),
        "capabilities": ["text generation", "code generation", "multilingual chat", "document analysis", "reasoning", "web search"],
        "input_types": ["text", "document", "image"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["multilingual tasks", "coding assistance", "European data compliance", "research", "document Q&A"],
        "limitations": ["frontier models require paid", "smaller ecosystem than OpenAI/Google", "web search limited on free"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "deepseek",
        "name": "DeepSeek",
        "description": "Chinese AI lab's powerful open-source models known for exceptional reasoning and coding at very low cost. DeepSeek-R1 matches frontier models at a fraction of the price.",
        "category_id": "chat-ai",
        "website_url": "https://chat.deepseek.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Web chat is free; API extremely affordable — $0.55/M input tokens for R1",
            api="API available: DeepSeek-R1 at $0.55/M input, $2.19/M output tokens",
        ),
        "capabilities": ["text generation", "advanced reasoning", "code generation", "math problem solving", "multilingual chat"],
        "input_types": ["text", "image"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["complex reasoning tasks", "math and science", "code generation", "cost-effective AI integration", "open-source deployment"],
        "limitations": ["data privacy concerns for enterprise", "Chinese-owned, some content restrictions", "image input limited to V3"],
        "verified_date": TODAY, "active": True,
    },

    # ── WRITING AI ───────────────────────────────────────────────────────────

    {
        "id": "sudowrite",
        "name": "Sudowrite",
        "description": "AI writing tool specifically designed for fiction writers. Helps with story generation, character development, brainstorming, and breaking writer's block.",
        "category_id": "writing-ai",
        "website_url": "https://www.sudowrite.com",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(
            credits="Free trial with limited words",
            features="Hobby plan starts at $19/month after trial",
            commercial=True,
        ),
        "capabilities": ["fiction writing", "story generation", "character development", "plot brainstorming", "scene expansion", "dialogue writing"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["novel writing", "short story creation", "screenplay writing", "overcoming writer's block", "narrative development"],
        "limitations": ["focused on fiction only", "no free tier after trial", "not for business/marketing copy"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "rytr",
        "name": "Rytr",
        "description": "Affordable AI writing assistant for short-form content. Supports 40+ use cases and 30+ languages with a permanent free tier.",
        "category_id": "writing-ai",
        "website_url": "https://rytr.me",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="10,000 characters per month on free tier",
            features="Free: limited characters, limited use cases; Saver $9/month: 100k chars",
        ),
        "capabilities": ["blog writing", "email writing", "ad copy", "social media content", "SEO meta tags", "product descriptions"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["blog posts", "email campaigns", "social media captions", "product descriptions", "multilingual content"],
        "limitations": ["10k chars/month free limit", "output quality below premium tools", "limited long-form support"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "quillbot",
        "name": "QuillBot",
        "description": "AI-powered paraphrasing and writing enhancement tool. Rewrites text in multiple modes including academic, creative, and concise styles.",
        "category_id": "writing-ai",
        "website_url": "https://quillbot.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="125 words per paraphrase on free tier",
            features="Free: 2 paraphrase modes, 125 word limit; Premium unlocks all 8 modes and unlimited length",
            api="No public API",
        ),
        "capabilities": ["paraphrasing", "grammar checking", "summarisation", "plagiarism detection", "citation generation", "translation"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["academic writing", "avoiding plagiarism", "improving writing clarity", "summarising research", "email rewriting"],
        "limitations": ["125 word limit on free", "paraphrasing focus", "plagiarism check requires paid"],
        "verified_date": TODAY, "active": True,
    },

    # ── RESEARCH AI ──────────────────────────────────────────────────────────

    {
        "id": "notebooklm",
        "name": "NotebookLM",
        "description": "Google's AI research assistant that lets you upload documents and have an AI answer questions exclusively from your sources. Generates audio podcasts, video overviews, and study materials from your content.",
        "category_id": "research-ai",
        "website_url": "https://notebooklm.google.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="50 chat queries/day; 3 audio/video generations per day",
            features="Free: 100 notebooks, 50 sources/notebook, 50,000 words/source; NotebookLM Plus available via Google One AI Premium",
            api="No public API",
            commercial=False,
        ),
        "capabilities": ["document Q&A", "source-grounded research", "audio podcast generation", "video overview generation", "mind maps", "flashcard creation", "deep research"],
        "input_types": ["document", "text", "audio", "video"],
        "output_types": ["text", "audio", "video"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["research paper analysis", "studying textbooks", "podcast generation from docs", "meeting notes synthesis", "literature review"],
        "limitations": ["answers only from uploaded sources", "50 chat queries/day on free", "no API access"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "elicit",
        "name": "Elicit",
        "description": "AI research assistant that searches academic papers, extracts key findings, and synthesises evidence. Purpose-built for systematic literature reviews.",
        "category_id": "research-ai",
        "website_url": "https://elicit.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            credits="5 free queries per week on free tier",
            features="Plus plan at $10/month: 100 queries/month with full extraction features",
            api="No public API",
        ),
        "capabilities": ["academic paper search", "data extraction from papers", "systematic literature review", "research synthesis", "citation management"],
        "input_types": ["text"],
        "output_types": ["text", "document"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["systematic reviews", "evidence synthesis", "clinical research", "academic writing support", "meta-analysis prep"],
        "limitations": ["5 free queries/week", "covers empirical research only", "limited to research available in its database"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "scite",
        "name": "Scite.ai",
        "description": "AI tool that shows how scientific papers have been cited — whether supporting, contrasting, or mentioning. Helps evaluate the credibility of research claims.",
        "category_id": "research-ai",
        "website_url": "https://scite.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: limited searches; Individual plan at $20/month for full access",
            api="API available on paid plans",
        ),
        "capabilities": ["citation analysis", "paper credibility scoring", "research discovery", "smart citations", "reference checking"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["verifying research claims", "academic publishing", "systematic reviews", "identifying contested findings", "research credibility assessment"],
        "limitations": ["limited free searches", "coverage depends on journal indexing", "full features require paid plan"],
        "verified_date": TODAY, "active": True,
    },

    # ── IMAGE GENERATION ─────────────────────────────────────────────────────

    {
        "id": "ideogram",
        "name": "Ideogram",
        "description": "AI image generator excelling at text rendering in images. Generates illustrations, logos, posters, and designs with accurate text that other models struggle to produce.",
        "category_id": "image-generation",
        "website_url": "https://ideogram.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            weekly="10 slow generation credits per week on free tier",
            features="Free outputs are public; paid plans add private generation. Plus at $7/month (annual): 1,000 priority credits",
            api="API available: $0.03/image (Turbo), $0.06 (Default), $0.10 (Quality)",
            commercial=True,
        ),
        "capabilities": ["text-to-image", "text rendering in images", "logo design", "poster creation", "typography art", "style presets"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["logo creation", "poster design", "social media graphics with text", "typography art", "marketing materials"],
        "limitations": ["free tier: 10 credits/week, public outputs only", "slower generation on free", "limited control vs professional tools"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "flux",
        "name": "FLUX by Black Forest Labs",
        "description": "State-of-the-art open-weight image generation model family (FLUX.1) from Black Forest Labs. Exceptional photorealism, prompt adherence, and detail. Available via API and local deployment.",
        "category_id": "image-generation",
        "website_url": "https://blackforestlabs.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="FLUX.1 [schnell] is completely free and open-source for local use; FLUX.1 [dev] open weights for non-commercial use; FLUX Pro via API is paid",
            api="FLUX Pro API: ~$0.055/image on various providers; FLUX [schnell] free via Replicate free tier",
            commercial=True,
        ),
        "capabilities": ["text-to-image", "photorealistic generation", "image-to-image", "fine-tuning", "portrait generation", "typography"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["photorealistic portraits", "product photography", "commercial image generation", "fine-tuned custom models", "high-fidelity renders"],
        "limitations": ["FLUX Pro requires API payment", "high VRAM needed for local use", "schnell model faster but lower quality than Pro"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "leonardo-ai",
        "name": "Leonardo.AI",
        "description": "AI image generation platform with fine-tuned models for game assets, concept art, and creative visuals. Strong community and model marketplace.",
        "category_id": "image-generation",
        "website_url": "https://leonardo.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="150 daily tokens (~30 standard images) on free tier",
            features="Free tier tokens reset daily; paid plans from $12/month for 8,500 tokens",
            api="API available on paid plans",
            commercial=True,
        ),
        "capabilities": ["text-to-image", "image-to-image", "inpainting", "fine-tuning", "video generation", "3D texture generation", "game asset creation"],
        "input_types": ["text", "image"],
        "output_types": ["image", "video"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["game asset creation", "concept art", "character design", "consistent style generation", "product mockups"],
        "limitations": ["150 daily tokens free (resets daily)", "fine-tuned models are community-maintained quality varies", "video generation credits limited"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "nightcafe",
        "name": "NightCafe",
        "description": "AI art generator with multiple models (Stable Diffusion, DALL-E, FLUX) and a strong community. Earn free credits daily by participating.",
        "category_id": "image-generation",
        "website_url": "https://creator.nightcafe.studio",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="5 free credits daily (earn more by liking/sharing)",
            features="Free credits earned through community activity; paid packs from $7.99",
            commercial=False,
        ),
        "capabilities": ["text-to-image", "style transfer", "image upscaling", "multiple AI models", "art community"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["AI art exploration", "community-driven creation", "style experiments", "creative hobby projects"],
        "limitations": ["no commercial use on free", "limited daily credits", "community-focused, less suited for professional work"],
        "verified_date": TODAY, "active": True,
    },

    # ── VIDEO GENERATION ─────────────────────────────────────────────────────

    {
        "id": "kling-ai",
        "name": "Kling AI",
        "description": "Kuaishou's professional AI video generator known for the smoothest motion physics of any AI video tool. Generates 4K videos with native audio and cinematic camera moves.",
        "category_id": "video-generation",
        "website_url": "https://klingai.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="66 free credits daily on free tier (~3-4 standard videos)",
            features="Free tier: standard quality only, watermark added; Standard plan $8.80/month after intro price for commercial use",
            watermark=True,
            watermark_details="Free tier videos include Kling watermark",
            api="API available via paid prepaid packages from $9.80",
            commercial=False,
        ),
        "capabilities": ["text-to-video", "image-to-video", "4K video generation", "lip sync", "camera motion control", "video extension", "native audio generation"],
        "input_types": ["text", "image"],
        "output_types": ["video"],
        "watermark_info": "Free tier adds Kling watermark to generated videos",
        "api_available": True,
        "best_use_cases": ["cinematic video production", "social media content", "advertising", "character animation", "4K creative videos"],
        "limitations": ["free tier: watermark, no commercial use, 66 credits/day", "paid plan needed for commercial rights"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "hailuo-ai",
        "name": "Hailuo AI",
        "description": "MiniMax's AI video generator (Hailuo 2.3) known for realistic motion, strong physics simulation, and high-quality image-to-video. Popular for social media content.",
        "category_id": "video-generation",
        "website_url": "https://hailuoai.video",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Limited free credits on signup; Standard plan at $19.90/month for 1,000 credits/month without watermark",
            watermark=True,
            watermark_details="Free tier videos include Hailuo watermark",
            api="API available: $0.28-$0.56 per clip depending on resolution",
            commercial=False,
        ),
        "capabilities": ["text-to-video", "image-to-video", "realistic motion", "physics simulation", "portrait animation"],
        "input_types": ["text", "image"],
        "output_types": ["video"],
        "watermark_info": "Free tier adds Hailuo watermark to generated videos",
        "api_available": True,
        "best_use_cases": ["realistic character animation", "social media clips", "portrait videos", "product showcase videos"],
        "limitations": ["free tier: watermark, limited credits", "Standard plan required for commercial use", "max 10s clips"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "luma-dream-machine",
        "name": "Luma Dream Machine",
        "description": "Luma AI's video generation platform built on their Ray model series. Known for physically accurate motion and cinematic quality. Integrates with Kling, Veo, and ElevenLabs.",
        "category_id": "video-generation",
        "website_url": "https://lumalabs.ai",
        "pricing_type": "Paid Only",
        "free_availability": False,
        "free_tier_details": None,
        "capabilities": ["text-to-video", "image-to-video", "3D scene generation", "camera motion control", "HDR video", "multi-model integration"],
        "input_types": ["text", "image"],
        "output_types": ["video"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["cinematic video production", "advertising", "3D visualization", "premium social content", "film prototyping"],
        "limitations": ["no free tier as of 2026", "paid plans from $25/month annual", "credits consumed per generation"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "heygen",
        "name": "HeyGen",
        "description": "AI avatar video creation platform used by 100,000+ businesses. Creates presenter videos with photorealistic AI avatars, supports 175+ languages with lip-sync translation.",
        "category_id": "video-generation",
        "website_url": "https://www.heygen.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="3 videos per month up to 1 minute each",
            features="Free: 1080p, 3 videos/month, watermark on exports; Creator $29/month: 600 credits, watermark removal",
            watermark=True,
            watermark_details="Free tier exports include HeyGen watermark",
            api="API available on paid plans",
            commercial=False,
        ),
        "capabilities": ["AI avatar video", "text-to-video with avatar", "video translation", "lip sync dubbing", "custom avatar creation", "streaming avatar"],
        "input_types": ["text", "audio", "video"],
        "output_types": ["video"],
        "watermark_info": "Free tier exports include HeyGen watermark",
        "api_available": True,
        "best_use_cases": ["corporate training videos", "marketing presentations", "multilingual video localisation", "personalized video at scale", "e-learning content"],
        "limitations": ["3 videos/month on free", "watermark on free tier", "custom avatar requires paid"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "invideo-ai",
        "name": "InVideo AI",
        "description": "AI video creation platform that turns text prompts or scripts into complete videos with stock footage, voiceover, and music. No video editing skills needed.",
        "category_id": "video-generation",
        "website_url": "https://invideo.io",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="10 free video exports per week (with watermark)",
            features="Free: 10 exports/week, watermark, limited stock media; Plus at $25/month: no watermark",
            watermark=True,
            watermark_details="Free tier videos include InVideo watermark",
            api="No public API",
            commercial=False,
        ),
        "capabilities": ["text-to-video", "script-to-video", "stock footage integration", "AI voiceover", "automated editing", "social media formats"],
        "input_types": ["text", "audio"],
        "output_types": ["video"],
        "watermark_info": "Free tier adds InVideo watermark",
        "api_available": False,
        "best_use_cases": ["social media videos", "YouTube content", "marketing videos", "explainer videos", "news videos"],
        "limitations": ["watermark on free", "10 exports/week free limit", "no custom AI video generation (uses stock footage)"],
        "verified_date": TODAY, "active": True,
    },

    # ── VOICE & AUDIO ────────────────────────────────────────────────────────

    {
        "id": "murf-ai",
        "name": "Murf AI",
        "description": "Professional AI voice generator with 200+ voices across 20+ languages. Used for voiceovers, explainer videos, podcasts, and e-learning content.",
        "category_id": "voice-audio",
        "website_url": "https://murf.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="10 minutes of voice generation on free tier",
            features="Free: 10 min generation, limited voices, no downloads without watermark; Basic $29/month",
            api="API available on paid plans",
            commercial=False,
        ),
        "capabilities": ["text-to-speech", "voice customisation", "AI voiceover", "voice changer", "pitch and emphasis control", "collaboration"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["explainer video voiceovers", "e-learning narration", "podcast production", "advertisement voiceovers", "IVR systems"],
        "limitations": ["10 min free; no commercial use on free", "200+ voices but quality varies", "requires subscription for professional use"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "suno-v4",
        "name": "Play.ht",
        "description": "AI text-to-speech and voice cloning platform with ultra-realistic voices. Supports 900+ voices across 140+ languages with emotion and tone controls.",
        "category_id": "voice-audio",
        "website_url": "https://play.ht",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="12,500 characters per month on free tier",
            features="Free: 12.5k chars/month, 2 cloned voices trial; Pro $39/month unlimited",
            api="API available on paid plans",
            commercial=False,
        ),
        "capabilities": ["text-to-speech", "voice cloning", "multilingual TTS", "emotion control", "real-time speech", "podcast generation"],
        "input_types": ["text", "audio"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["podcast production", "audiobook creation", "multilingual content", "accessibility tools", "voice cloning"],
        "limitations": ["12.5k chars/month free", "commercial use requires paid plan", "cloning quality depends on sample length"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "adobe-podcast",
        "name": "Adobe Podcast (Enhance Speech)",
        "description": "Adobe's AI audio enhancement tool that removes background noise, improves microphone quality to studio-grade, and cleans up voice recordings automatically.",
        "category_id": "voice-audio",
        "website_url": "https://podcast.adobe.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Enhance Speech is free for basic use; full Adobe Podcast features in Creative Cloud",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["audio enhancement", "noise removal", "microphone quality improvement", "speech clarity", "background removal"],
        "input_types": ["audio"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["podcast audio cleanup", "meeting recording enhancement", "YouTube video audio", "interview recordings", "remote work audio"],
        "limitations": ["upload size limits on free", "best features in Creative Cloud", "voice-only (no music processing)"],
        "verified_date": TODAY, "active": True,
    },

    # ── MUSIC GENERATION ─────────────────────────────────────────────────────

    {
        "id": "soundraw",
        "name": "Soundraw",
        "description": "AI music generator for creating royalty-free background music by mood, genre, and tempo. Customise length and structure for video and content creation.",
        "category_id": "music-generation",
        "website_url": "https://soundraw.io",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: generate unlimited music, no downloads without subscription; Artist plan $16.99/month",
            gen_limit="Unlimited generation on free, but download requires paid",
            commercial=False,
        ),
        "capabilities": ["AI music generation", "mood-based composition", "tempo customisation", "genre selection", "stem download", "royalty-free music"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["video background music", "YouTube content", "podcast intros", "social media audio", "game music"],
        "limitations": ["no download on free tier", "commercial use requires paid plan", "less creative control than Suno"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "mubert",
        "name": "Mubert",
        "description": "AI music streaming and generation platform that creates continuous, adaptive background music. Strong API for developers building apps with dynamic soundtracks.",
        "category_id": "music-generation",
        "website_url": "https://mubert.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="25 free track generations per month",
            features="Free: 25 tracks/month, 25s max, non-commercial; Creator $14/month for commercial use",
            commercial=False,
        ),
        "capabilities": ["AI music generation", "adaptive music streaming", "mood-based generation", "API music generation", "royalty-free tracks"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["app background music", "streaming platform integrations", "podcast intros", "game audio", "meditation apps"],
        "limitations": ["25 free tracks/month", "non-commercial on free", "less creative than Suno for full songs"],
        "verified_date": TODAY, "active": True,
    },

    # ── CODING AI ────────────────────────────────────────────────────────────

    {
        "id": "bolt-new",
        "name": "Bolt.new",
        "description": "Browser-based AI full-stack development environment by StackBlitz. Generates complete apps from prompts and lets you edit, run, and deploy directly in the browser without local setup.",
        "category_id": "coding-ai",
        "website_url": "https://bolt.new",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="150,000–300,000 tokens per day on free tier",
            features="Free: token-limited daily; Starter $20/month: 10M tokens; Pro $50/month: 33M tokens",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["full-stack app generation", "browser-based coding", "React/Vue/Next.js/Svelte support", "one-click deployment", "database integration", "real-time preview"],
        "input_types": ["text", "image"],
        "output_types": ["code"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["rapid prototyping", "full-stack app generation", "landing pages", "SaaS MVPs", "hackathon projects"],
        "limitations": ["token limits on free tier", "complex apps hit context limits", "best for React/TypeScript stack"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "v0-dev",
        "name": "v0 by Vercel",
        "description": "Vercel's AI-powered UI generation tool. Converts text prompts and screenshots into clean React + Tailwind CSS component code. Best-in-class for frontend UI generation.",
        "category_id": "coding-ai",
        "website_url": "https://v0.dev",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="~$5 worth of free token credits monthly",
            features="Free: limited monthly credits (~5 messages/day); Premium $20/month: 200 messages/day",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["UI component generation", "React code generation", "Tailwind CSS styling", "screenshot-to-code", "component library", "Next.js integration"],
        "input_types": ["text", "image"],
        "output_types": ["code"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["UI component generation", "landing page design", "dashboard prototyping", "converting designs to code", "Next.js development"],
        "limitations": ["limited free monthly credits", "React/Next.js ecosystem focus", "complex state logic needs manual work"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "replit-ai",
        "name": "Replit AI",
        "description": "AI-powered coding environment in the browser with agents that can build, run, and debug complete applications. Strong for beginners and rapid deployment.",
        "category_id": "coding-ai",
        "website_url": "https://replit.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: basic IDE with limited AI features; Core $25/month for full AI agent access",
            api="No public API for AI features",
            commercial=True,
        ),
        "capabilities": ["full-stack app generation", "browser-based IDE", "code execution", "deployment", "collaboration", "AI agent coding"],
        "input_types": ["text", "code"],
        "output_types": ["code"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["learning to code", "rapid app deployment", "collaborative coding", "Python/JavaScript apps", "hackathon projects"],
        "limitations": ["free tier limited AI features", "slower than local IDE", "Core $25/month for AI agent"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "tabnine",
        "name": "Tabnine",
        "description": "AI code completion tool that runs locally for privacy. Supports all major IDEs and keeps your code on-device — a key differentiator for enterprise use.",
        "category_id": "coding-ai",
        "website_url": "https://www.tabnine.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: basic completions on cloud model; Pro $12/month for full AI and local model",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["code completion", "code generation", "code review", "local model support", "privacy-preserving AI", "multi-language support"],
        "input_types": ["code", "text"],
        "output_types": ["code"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["enterprise coding with data privacy", "regulated industries", "offline coding assistance", "team code suggestions"],
        "limitations": ["free tier limited to basic completions", "local model requires powerful hardware", "smaller training dataset than Copilot"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "lovable",
        "name": "Lovable",
        "description": "AI full-stack app builder that generates, deploys, and hosts complete web applications from conversational prompts. No code required — point and click editing.",
        "category_id": "coding-ai",
        "website_url": "https://lovable.dev",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="5 credits per day (1 credit ≈ 1 prompt response)",
            features="Free: 5 credits/day, public projects only; Starter $20/month: 100 credits/month, private projects",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["full-stack app generation", "one-click deployment", "Supabase integration", "visual editing", "React generation", "no-code editing"],
        "input_types": ["text", "image"],
        "output_types": ["code"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["SaaS MVP building", "rapid prototyping", "non-technical founders", "startup MVPs", "internal tools"],
        "limitations": ["5 credits/day on free", "public projects only on free", "complex apps need paid plan"],
        "verified_date": TODAY, "active": True,
    },

    # ── DESIGN AI ────────────────────────────────────────────────────────────

    {
        "id": "figma-ai",
        "name": "Figma AI",
        "description": "Figma's suite of AI features including Make Designs (text-to-design), Rename Layers, Prototype from image, and AI-powered design suggestions built into the leading design tool.",
        "category_id": "design-ai",
        "website_url": "https://www.figma.com/ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="AI features included in Figma Starter (free up to 3 files); Professional $15/editor/month unlocks full AI",
            api="No dedicated AI API; REST API available",
            commercial=True,
        ),
        "capabilities": ["text-to-design", "layer renaming", "design generation", "prototype creation", "component search", "design suggestions"],
        "input_types": ["text", "image"],
        "output_types": ["image", "prototype"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["UI design", "design system creation", "rapid prototyping", "collaborative design", "developer handoff"],
        "limitations": ["3 file limit on free Starter plan", "full AI requires Professional plan", "design AI still maturing"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "microsoft-designer",
        "name": "Microsoft Designer",
        "description": "Microsoft's free AI-powered graphic design tool. Creates social media posts, invitations, and marketing materials from text prompts with DALL-E image generation.",
        "category_id": "design-ai",
        "website_url": "https://designer.microsoft.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free with Microsoft account; Designer Premium included in Microsoft 365 Personal/Family",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["AI image generation", "social media graphics", "invitation design", "poster creation", "logo design", "template customisation"],
        "input_types": ["text", "image"],
        "output_types": ["image", "document"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["social media posts", "birthday invitations", "event flyers", "presentation slides", "quick marketing graphics"],
        "limitations": ["less powerful than Canva for professional use", "limited template variety", "requires Microsoft account"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "looka",
        "name": "Looka",
        "description": "AI-powered logo maker and brand identity tool. Generates professional logo options from your brand preferences in seconds, with full brand kit generation.",
        "category_id": "design-ai",
        "website_url": "https://looka.com",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free to design logos; download requires payment. Basic logo from $20 one-time; Brand Kit subscription $96/year",
            gen_limit="Unlimited logo generation (free to explore, pay to download)",
            commercial=True,
        ),
        "capabilities": ["logo generation", "brand identity creation", "color palette generation", "typography selection", "brand kit creation", "business card design"],
        "input_types": ["text"],
        "output_types": ["image", "document"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["startup logo creation", "small business branding", "brand identity package", "social media branding"],
        "limitations": ["free to design but must pay to download", "limited customisation depth vs professional designers", "logo ownership on Basic plan only"],
        "verified_date": TODAY, "active": True,
    },

    # ── PRODUCTIVITY AI ──────────────────────────────────────────────────────

    {
        "id": "fireflies-ai",
        "name": "Fireflies.ai",
        "description": "AI meeting assistant that automatically records, transcribes, and summarises video calls across Zoom, Teams, Google Meet. Searchable meeting history.",
        "category_id": "productivity-ai",
        "website_url": "https://fireflies.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="800 minutes of storage on free tier",
            features="Free: 800 min storage, limited AI summaries, 3 seats; Pro $18/seat/month for unlimited",
            api="API available on paid plans",
            commercial=True,
        ),
        "capabilities": ["meeting transcription", "meeting summarisation", "action item extraction", "meeting search", "CRM integration", "meeting analytics"],
        "input_types": ["audio", "video"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["sales call recording", "team meeting notes", "customer interview analysis", "compliance recording", "meeting search"],
        "limitations": ["800 min storage on free", "limited AI summaries on free", "Pro required for CRM integrations"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "reclaim-ai",
        "name": "Reclaim.ai",
        "description": "AI scheduling assistant that automatically finds the best times for tasks, meetings, and habits in your calendar. Integrates with Google Calendar and Slack.",
        "category_id": "productivity-ai",
        "website_url": "https://reclaim.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: 1 user, core scheduling features; Starter $8/user/month for team features",
            api="API available on paid plans",
            commercial=True,
        ),
        "capabilities": ["AI scheduling", "habit tracking", "meeting buffer management", "focus time blocking", "task time estimation", "team scheduling"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["deep work scheduling", "meeting management", "work-life balance", "team coordination", "calendar optimization"],
        "limitations": ["Google Calendar only on free", "Outlook requires paid plan", "AI predictions improve with more data over time"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "motion",
        "name": "Motion",
        "description": "AI-powered project management and scheduling tool that automatically plans your day by prioritising tasks and scheduling them around meetings.",
        "category_id": "productivity-ai",
        "website_url": "https://usemotion.com",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(
            credits="7-day free trial",
            features="Individual at $19/month after trial; Business at $12/user/month annual",
            commercial=True,
        ),
        "capabilities": ["AI task scheduling", "project management", "automatic daily planning", "meeting scheduling", "deadline tracking", "team coordination"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["individual productivity", "project timeline management", "deadline-driven work", "team task distribution"],
        "limitations": ["7-day trial only, then $19/month", "no permanent free tier", "calendar integration required"],
        "verified_date": TODAY, "active": True,
    },

    # ── DOCUMENT AI ──────────────────────────────────────────────────────────

    {
        "id": "humata-ai",
        "name": "Humata AI",
        "description": "AI tool for reading, summarising, and chatting with any PDF or document. Ask complex questions and get instant answers with citations from your files.",
        "category_id": "document-ai",
        "website_url": "https://www.humata.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="60 questions per month on free tier",
            features="Free: 60 queries/month, 60 pages per file; Expert $9.99/month for unlimited",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["document Q&A", "PDF summarisation", "multi-document analysis", "citation extraction", "document comparison"],
        "input_types": ["document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["legal document review", "research paper analysis", "contract review", "academic research", "business report summarisation"],
        "limitations": ["60 questions/month on free", "60 page limit per file on free", "no public API"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "docugpt",
        "name": "DocuChat",
        "description": "Upload documents, PDFs, and websites and chat with an AI trained specifically on your content. Build custom chatbots from your knowledge base.",
        "category_id": "document-ai",
        "website_url": "https://www.docuchat.io",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: 1 chatbot, 1 document, 50 messages/month; Starter $19/month for expanded limits",
            api="API available on paid plans",
            commercial=True,
        ),
        "capabilities": ["document Q&A", "custom chatbot creation", "knowledge base chat", "website scraping", "multi-format support"],
        "input_types": ["document", "text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["customer support chatbots", "internal knowledge base", "FAQ automation", "document Q&A for teams"],
        "limitations": ["1 chatbot on free", "50 messages/month free", "commercial deployment requires paid plan"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "reducto",
        "name": "Reducto",
        "description": "Enterprise-grade document parsing API that converts complex PDFs, tables, and scanned documents into structured data with high accuracy using AI.",
        "category_id": "document-ai",
        "website_url": "https://reducto.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="500 free document pages per month",
            features="Free: 500 pages/month; Growth $49/month: 10,000 pages",
            api="API-first product; free tier available",
            commercial=True,
        ),
        "capabilities": ["PDF parsing", "table extraction", "OCR", "structured data extraction", "form processing", "financial document parsing"],
        "input_types": ["document"],
        "output_types": ["text", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["financial document processing", "invoice extraction", "legal document parsing", "research paper data extraction", "enterprise document workflows"],
        "limitations": ["500 pages/month on free", "API-only (no GUI)", "complex tables may need fine-tuning"],
        "verified_date": TODAY, "active": True,
    },

    # ── TRANSLATION AI ───────────────────────────────────────────────────────

    {
        "id": "lecto",
        "name": "Lecto AI",
        "description": "Developer-focused AI translation API supporting 90+ languages at significantly lower cost than Google Translate and DeepL. Designed for high-volume translation workflows.",
        "category_id": "translation-ai",
        "website_url": "https://lecto.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="1,000 free translation requests per month",
            features="Free: 1,000 requests/month; paid tiers from $9/month by volume",
            api="API-first product",
            commercial=True,
        ),
        "capabilities": ["text translation", "API translation", "bulk translation", "90+ language support", "low-cost high-volume translation"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["app localisation", "high-volume content translation", "e-commerce product translation", "multilingual SaaS"],
        "limitations": ["1,000 requests/month free", "lower quality than DeepL for nuanced text", "API-only (no web interface)"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "papago",
        "name": "Papago",
        "description": "NAVER's AI translation service, particularly strong for Asian languages (Korean, Japanese, Chinese) and under-resourced Asian languages that Google struggles with.",
        "category_id": "translation-ai",
        "website_url": "https://papago.naver.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Web app is free; API free tier: 10,000 characters/day",
            api="API free: 10,000 chars/day; paid for higher volume",
            commercial=True,
        ),
        "capabilities": ["text translation", "image translation", "voice translation", "document translation", "Korean/Japanese/Chinese specialisation"],
        "input_types": ["text", "image", "audio"],
        "output_types": ["text", "audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["Korean/Japanese content translation", "Asian language localisation", "K-drama subtitles", "Asian e-commerce", "travel in Asia"],
        "limitations": ["covers fewer languages than Google Translate", "weaker for non-Asian language pairs", "API free tier limited"],
        "verified_date": TODAY, "active": True,
    },

    # ── AI AGENTS ────────────────────────────────────────────────────────────

    {
        "id": "n8n-ai",
        "name": "n8n",
        "description": "Open-source workflow automation platform with AI agent capabilities. Connect 400+ apps and build AI-powered automations with visual workflow builder. Self-hostable.",
        "category_id": "ai-agents",
        "website_url": "https://n8n.io",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Self-hosted: completely free and open source; Cloud free trial then $24/month Starter",
            gen_limit="Unlimited on self-hosted",
            api="Full REST API",
            commercial=True,
        ),
        "capabilities": ["workflow automation", "AI agent creation", "400+ integrations", "webhook triggers", "data transformation", "self-hosting"],
        "input_types": ["text", "code"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["business process automation", "AI-powered workflows", "API orchestration", "data pipelines", "enterprise automation"],
        "limitations": ["self-hosted setup requires technical knowledge", "cloud tier has execution limits", "complex workflows need debugging skill"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "zapier-ai",
        "name": "Zapier AI",
        "description": "Zapier's AI-powered automation layer that creates Zaps (automations) from natural language descriptions and includes AI-powered steps for content generation within workflows.",
        "category_id": "ai-agents",
        "website_url": "https://zapier.com/ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="100 tasks per month on free tier",
            features="Free: 100 tasks/month, 5 Zaps; Starter $29.99/month: 750 tasks",
            api="No public API (use their platform)",
            commercial=True,
        ),
        "capabilities": ["workflow automation", "natural language automation creation", "AI content generation in workflows", "6,000+ app integrations", "multi-step automations"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["no-code automation", "marketing workflows", "CRM automation", "email automation", "social media scheduling"],
        "limitations": ["100 tasks/month on free", "5 Zap limit on free", "complex logic limited without code"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "microsoft-copilot-studio",
        "name": "Microsoft Copilot Studio",
        "description": "Low-code platform for building custom AI agents and Copilots. Integrates with Microsoft 365, Teams, and enterprise data sources. Formerly Power Virtual Agents.",
        "category_id": "ai-agents",
        "website_url": "https://www.microsoft.com/en-us/microsoft-copilot/microsoft-copilot-studio",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(
            features="25,000 free messages/month for existing Microsoft 365 customers; standalone $200/month for 25k messages",
            credits="25,000 messages/month included with eligible Microsoft 365 plans",
            commercial=True,
        ),
        "capabilities": ["custom AI agent creation", "enterprise chatbot", "Microsoft 365 integration", "Teams integration", "knowledge base integration", "multi-channel deployment"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["enterprise customer service", "HR chatbots", "IT helpdesk automation", "internal knowledge bots", "Teams-based assistants"],
        "limitations": ["requires Microsoft ecosystem", "25k messages/month on M365 plans", "standalone expensive at $200/month"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "phidata",
        "name": "Phidata",
        "description": "Open-source framework for building AI agents with memory, knowledge, and tools. Includes pre-built agents for web search, finance, research, and more.",
        "category_id": "ai-agents",
        "website_url": "https://www.phidata.com",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Framework is free and open-source",
            features="Framework free; requires own LLM API keys (costs depend on provider)",
            commercial=True,
        ),
        "capabilities": ["AI agent creation", "multi-agent teams", "memory management", "knowledge base integration", "tool use", "structured outputs"],
        "input_types": ["text", "code"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["AI research agents", "financial analysis agents", "web scraping agents", "multi-agent pipelines", "Python-based agent development"],
        "limitations": ["requires programming knowledge", "needs LLM API keys", "cloud platform in beta"],
        "verified_date": TODAY, "active": True,
    },
]


def seed():
    db = get_db()
    col = db.collection("tools")
    for tool in NEW_TOOLS:
        doc_id = tool["id"]
        col.document(doc_id).set(tool)
        print(f"  ✓ {tool['name']} ({tool['category_id']}) — {tool['pricing_type']}")
    print(f"\nSeeded {len(NEW_TOOLS)} new tools.")


if __name__ == "__main__":
    seed()
