"""
Seed batch 3 — fills thin categories to 8-10 tools each.
Covers: writing-ai, research-ai, design-ai, document-ai,
        productivity-ai, music-generation, translation-ai, ai-agents

Idempotent — uses tool ID as Firestore document ID.

Usage:
    cd backend
    python -m scripts.seed_tools_batch3
"""

import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.db.firestore_client import get_db

TODAY = datetime.date.today().isoformat()

def ftd(credits=None, gen_limit=None, daily=None, monthly=None, watermark=False,
        watermark_details=None, features=None, api=None, commercial=True):
    return {
        "credits": credits, "generation_limit": gen_limit,
        "daily_limit": daily, "monthly_limit": monthly,
        "has_watermark": watermark, "watermark_details": watermark_details,
        "feature_restrictions": features, "api_restrictions": api,
        "commercial_use_allowed": commercial,
    }

TOOLS = [

    # ── WRITING AI (was 6, target 9) ─────────────────────────────────────

    {
        "id": "wordtune",
        "name": "Wordtune",
        "description": "AI writing assistant that rewrites, rephrases, and improves existing text. Offers multiple tone and style options. Strong for non-native English speakers and professionals who need clearer writing.",
        "category_id": "writing-ai",
        "website_url": "https://www.wordtune.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="10 rewrites and 10 AI suggestions per day on free plan",
            features="Free: 10 rewrites/day, 3 document summaries/month, unlimited spelling/grammar corrections; Advanced $4.89/month annual",
            api="No public API",
        ),
        "capabilities": ["text rewriting", "paraphrasing", "tone adjustment", "sentence shortening", "sentence expansion", "AI summarisation", "grammar correction"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["improving clarity of existing writing", "rephrasing for different tones", "non-native English writing", "email and report refinement"],
        "limitations": ["10 rewrites/day on free", "rewrites only (not generative)", "works on existing text not blank page"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "hemingway-editor",
        "name": "Hemingway Editor",
        "description": "Writing clarity tool that highlights complex sentences, passive voice, adverbs, and readability issues. The web version is completely free. A desktop app is available for one-time purchase.",
        "category_id": "writing-ai",
        "website_url": "https://hemingwayapp.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited use on web browser — completely free",
            features="Web app fully free; Desktop app is a one-time $19.99 purchase; AI rewrite feature requires paid subscription",
            api="No public API",
        ),
        "capabilities": ["readability scoring", "passive voice detection", "adverb highlighting", "complex sentence detection", "grade level analysis"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["improving writing clarity", "academic writing", "blog posts", "content editing", "reducing complex sentences"],
        "limitations": ["no generative AI (editing only)", "AI rewrite requires paid", "no API access"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "gamma-app",
        "name": "Gamma",
        "description": "AI presentation and document builder that creates polished slide decks, documents, and web pages from a text prompt in seconds. Strong design output with minimal effort.",
        "category_id": "writing-ai",
        "website_url": "https://gamma.app",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            credits="400 AI credits on signup (one-time, does not refill on free plan)",
            features="Free: 400 starter credits one-time only; Plus $8/month annual: 400 credits/month; Pro $18/month: 1,000 credits/month",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["AI presentation generation", "document creation", "web page creation", "slide design", "template customisation", "image generation"],
        "input_types": ["text"],
        "output_types": ["document", "image"],
        "watermark_info": "Gamma branding on free exports",
        "api_available": False,
        "best_use_cases": ["pitch decks", "business presentations", "reports", "landing pages", "educational materials"],
        "limitations": ["400 credits one-time on free (not monthly)", "Gamma watermark on free exports", "no API access"],
        "verified_date": TODAY, "active": True,
    },

    # ── RESEARCH AI (was 5, target 8) ────────────────────────────────────

    {
        "id": "research-rabbit",
        "name": "ResearchRabbit",
        "description": "Free literature discovery and citation mapping tool. Visualises connections between academic papers through interactive networks. Helps researchers find related work they would have missed.",
        "category_id": "research-ai",
        "website_url": "https://www.researchrabbit.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Core features completely free; premium plan announced for advanced search",
            features="Free: unlimited paper collections, citation mapping, author tracking, collaboration; Premium tier announced with advanced AI features",
            api="No public API",
        ),
        "capabilities": ["citation mapping", "paper discovery", "literature network visualisation", "author tracking", "collection management", "related paper recommendations"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["academic literature review", "finding related papers", "mapping research fields", "systematic reviews", "tracking author output"],
        "limitations": ["covers published academic papers only", "premium tier coming with advanced features", "no document upload (paper-based discovery only)"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "semantic-scholar",
        "name": "Semantic Scholar",
        "description": "Free AI-powered academic search engine from Allen Institute for AI. Covers 220M+ papers with semantic search, citation analysis, TLDR summaries, and paper recommendations.",
        "category_id": "research-ai",
        "website_url": "https://www.semanticscholar.org",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Fully free — no account required for search",
            api="API available: free tier 100 requests/5min; higher limits on request",
        ),
        "capabilities": ["academic paper search", "AI-generated TLDR summaries", "citation analysis", "semantic search", "paper recommendations", "author profiles", "research feeds"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["academic research", "finding papers on specific topics", "citation analysis", "literature discovery", "staying current in a field"],
        "limitations": ["academic papers only", "TLDR quality varies by paper", "no document upload or Q&A on your own files"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "connected-papers",
        "name": "Connected Papers",
        "description": "Visual tool for exploring academic papers related to a given paper. Creates a graph of related work based on co-citation and bibliographic coupling — helps find relevant prior and derivative work.",
        "category_id": "research-ai",
        "website_url": "https://www.connectedpapers.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="5 free graphs per month on free plan",
            features="Free: 5 graphs/month; Academic $3/month: unlimited graphs",
            api="No public API",
        ),
        "capabilities": ["paper relationship visualisation", "citation network mapping", "prior work discovery", "derivative work discovery", "literature gap identification"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["finding related papers", "literature review scoping", "understanding a research field", "identifying seminal works", "finding derivative studies"],
        "limitations": ["5 graphs/month on free", "academic papers only", "graph generation can be slow for niche topics"],
        "verified_date": TODAY, "active": True,
    },

    # ── DESIGN AI (was 5, target 8) ──────────────────────────────────────

    {
        "id": "framer-ai",
        "name": "Framer AI",
        "description": "AI-powered website builder that generates full websites from text prompts. Framer AI creates production-ready responsive websites with animations. Also functions as a professional no-code web design tool.",
        "category_id": "design-ai",
        "website_url": "https://www.framer.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free plan: design and preview only (no custom domain, no publishing to live site); Basic $10/month annual to publish",
            api="REST API available for CMS",
            commercial=True,
        ),
        "capabilities": ["AI website generation", "no-code web design", "responsive layouts", "animation", "CMS", "prototype creation", "component design"],
        "input_types": ["text", "image"],
        "output_types": ["prototype", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["portfolio websites", "landing pages", "startup websites", "rapid prototyping", "design system creation"],
        "limitations": ["free plan cannot publish to live domain", "Basic $10/month to go live", "AI site generation uses AI credits"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "adobe-express",
        "name": "Adobe Express",
        "description": "Adobe's free AI-powered design tool for social media posts, videos, PDFs, and marketing materials. Includes thousands of templates, Adobe Stock assets, and generative AI features powered by Adobe Firefly.",
        "category_id": "design-ai",
        "website_url": "https://www.adobe.com/express",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free plan: core templates, limited assets, basic AI features; Premium $9.99/month: 250 Firefly generative credits, brand kits, 100GB storage",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["social media design", "video creation", "PDF creation", "AI image generation", "background removal", "template customisation", "brand kits"],
        "input_types": ["text", "image"],
        "output_types": ["image", "document"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["social media graphics", "marketing materials", "quick videos", "flyers and posters", "business documents"],
        "limitations": ["limited generative AI credits on free", "advanced brand features require Premium", "less powerful than full Creative Cloud"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "recraft",
        "name": "Recraft",
        "description": "AI image and vector generation tool specialising in brand-consistent design assets. Unique for generating SVG vectors, icons, and illustrations in a consistent style — particularly strong for product and UI design.",
        "category_id": "design-ai",
        "website_url": "https://www.recraft.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="50 free image generations per month",
            features="Free: 50 generations/month, community visibility on free outputs; Pro $12/month: 1,000 generations, private outputs",
            api="API available on paid plans",
            commercial=True,
        ),
        "capabilities": ["AI image generation", "vector SVG generation", "icon generation", "illustration creation", "brand style consistency", "image editing", "UI asset creation"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["brand illustration systems", "icon sets", "product UI assets", "consistent style generation", "vector art creation"],
        "limitations": ["50 free generations/month", "free outputs are public", "SVG quality varies by complexity"],
        "verified_date": TODAY, "active": True,
    },

    # ── DOCUMENT AI (was 5, target 8) ────────────────────────────────────

    {
        "id": "mathpix",
        "name": "Mathpix",
        "description": "AI tool for converting handwritten and printed math, chemistry, and scientific notation into LaTeX, MathML, or digital text. Essential for researchers, students, and scientists working with equations.",
        "category_id": "document-ai",
        "website_url": "https://mathpix.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="20 free snips per month on free plan",
            features="Free: 20 equation snips/month; Pro $4.99/month: 5,000 snips/month",
            api="API free tier: 1,000 calls/month",
        ),
        "capabilities": ["handwritten math recognition", "equation to LaTeX", "PDF scientific conversion", "chemistry notation recognition", "table extraction", "diagram digitisation"],
        "input_types": ["image", "document"],
        "output_types": ["text", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["converting handwritten equations", "digitising scientific papers", "LaTeX generation", "chemistry formula recognition", "academic document processing"],
        "limitations": ["20 free snips/month", "best for STEM content specifically", "complex diagrams may need manual correction"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "pdf-ai",
        "name": "PDF.ai",
        "description": "Chat with any PDF document — ask questions, get summaries, extract data. Supports large documents and multiple PDFs simultaneously. Simple, focused interface for document Q&A.",
        "category_id": "document-ai",
        "website_url": "https://pdf.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            daily="1 PDF per day, up to 120 pages, 10MB on free plan",
            features="Free: 1 PDF/day, 120 pages max, 10MB; Starter $12/month: 50 PDFs/day",
            api="No public API",
        ),
        "capabilities": ["PDF Q&A", "document summarisation", "data extraction", "multi-document chat", "citation generation"],
        "input_types": ["document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["research paper Q&A", "legal document review", "contract analysis", "textbook study", "report summarisation"],
        "limitations": ["1 PDF/day on free", "120 page limit on free", "no API access"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "descript",
        "name": "Descript",
        "description": "AI-powered audio and video editor that uses text-based editing — edit your media by editing the transcript. Includes AI features: filler-word removal, Studio Sound noise cleanup, Overdub voice cloning, and screen recording.",
        "category_id": "document-ai",
        "website_url": "https://www.descript.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="60 minutes of media per month on free plan",
            features="Free: 60 min/month, 100 AI credits one-time, 720p exports with watermark; Hobbyist $16/month annual: no watermark",
            watermark=True,
            watermark_details="Free plan exports include Descript watermark at 720p",
            api="No public API",
            commercial=False,
        ),
        "capabilities": ["text-based video editing", "audio editing", "transcription", "filler word removal", "noise removal", "voice cloning (Overdub)", "screen recording", "podcast editing"],
        "input_types": ["audio", "video"],
        "output_types": ["audio", "video", "text"],
        "watermark_info": "Free plan exports include watermark at 720p",
        "api_available": False,
        "best_use_cases": ["podcast production", "YouTube video editing", "interview editing", "screen recording with AI captions", "corporate video creation"],
        "limitations": ["60 min/month free", "watermark on free exports", "voice cloning quality requires good audio samples"],
        "verified_date": TODAY, "active": True,
    },

    # ── PRODUCTIVITY AI (was 5, target 8) ────────────────────────────────

    {
        "id": "make",
        "name": "Make (formerly Integromat)",
        "description": "Visual automation platform for connecting apps and building complex workflows without code. More powerful than Zapier for complex multi-step automations. Free tier includes 1,000 operations/month with 2 active scenarios.",
        "category_id": "productivity-ai",
        "website_url": "https://www.make.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="1,000 operations per month on free plan",
            features="Free: 1,000 ops/month, 2 active scenarios, 15-min minimum interval; Core $9/month annual: 10,000 ops/month",
            api="Full API access on all plans",
            commercial=True,
        ),
        "capabilities": ["visual workflow automation", "3,000+ app integrations", "multi-step automation", "data transformation", "webhook support", "scheduling", "AI provider integrations"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["business process automation", "marketing workflows", "data pipeline creation", "CRM automation", "complex multi-step integrations"],
        "limitations": ["1,000 ops/month on free", "only 2 active scenarios on free", "15-min minimum polling on free"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "mem-ai",
        "name": "Mem",
        "description": "AI-first note-taking app that automatically organises notes and surfaces relevant information. Uses AI to find connections between notes, draft content, and answer questions from your knowledge base.",
        "category_id": "productivity-ai",
        "website_url": "https://mem.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: core note-taking with basic AI; Pro $14.99/month: unlimited AI features, smart search, AI drafting",
            api="No public API",
            commercial=True,
        ),
        "capabilities": ["AI note-taking", "automatic organisation", "knowledge base Q&A", "smart search", "AI drafting", "connection discovery between notes"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["personal knowledge management", "meeting notes", "research organisation", "writing assistance from notes", "team knowledge base"],
        "limitations": ["free AI features limited", "full AI requires Pro $14.99/month", "web and mobile only"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "todoist-ai",
        "name": "Todoist AI Assistant",
        "description": "Todoist's built-in AI assistant that breaks down tasks, estimates effort, and suggests sub-tasks. Part of the Todoist task manager — AI features are layered on top of one of the most popular to-do apps.",
        "category_id": "productivity-ai",
        "website_url": "https://todoist.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free plan: 5 active projects, basic AI suggestions; Pro $4/month annual: unlimited projects, full AI assistant, reminders",
            api="REST API available on all plans",
            commercial=True,
        ),
        "capabilities": ["AI task breakdown", "effort estimation", "sub-task suggestions", "natural language task entry", "project planning", "team collaboration"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["personal task management", "project planning", "team task coordination", "daily planning with AI", "GTD workflow"],
        "limitations": ["5 active projects on free", "AI features limited on free", "Pro $4/month for full AI assistant"],
        "verified_date": TODAY, "active": True,
    },

    # ── MUSIC GENERATION (was 4, target 7) ───────────────────────────────

    {
        "id": "boomy",
        "name": "Boomy",
        "description": "AI music creation platform that generates original songs in seconds and lets you release them to streaming platforms like Spotify. One of the easiest ways to create and publish AI-generated music.",
        "category_id": "music-generation",
        "website_url": "https://boomy.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited song creation on free plan",
            features="Free: unlimited song creation, save up to 25 tracks, release 1 project (up to 3 songs); Creator $9.99/month: 500 saves, commercial rights, MP3 downloads",
            commercial=False,
        ),
        "capabilities": ["AI song generation", "music style selection", "streaming release", "song customisation", "lyric generation"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["quick music creation", "publishing to streaming platforms", "background music", "hobbyist music production", "social media content"],
        "limitations": ["save limit of 25 tracks on free", "no commercial use on free", "limited control over musical structure", "MP3 downloads require paid"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "loudly",
        "name": "Loudly",
        "description": "AI music generator focused on background and production music. Creates royalty-free tracks by mood, genre, and tempo. Strong library of AI-generated stems for mixing.",
        "category_id": "music-generation",
        "website_url": "https://www.loudly.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="10 free song generations per month",
            features="Free: 10 generations/month, limited downloads; Pro $7.99/month: 100 generations, commercial licence",
            commercial=False,
        ),
        "capabilities": ["AI music generation", "mood-based generation", "genre selection", "stem separation", "royalty-free tracks", "tempo control"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["video background music", "podcast intros", "content creation", "game audio", "royalty-free library"],
        "limitations": ["10 free generations/month", "no commercial use on free", "less creative than Suno for full songs"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "aiva",
        "name": "AIVA",
        "description": "AI music composer that creates original scores in various classical and cinematic styles. Registered composer with SACEM. Used by game developers, filmmakers, and advertisers for custom soundtracks.",
        "category_id": "music-generation",
        "website_url": "https://www.aiva.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="3 downloads per month on free plan",
            features="Free: create unlimited tracks, download 3/month (MP3 only), non-commercial use; Standard $15/month: unlimited downloads, commercial rights",
            commercial=False,
        ),
        "capabilities": ["AI composition", "orchestral music generation", "cinematic scoring", "style presets", "MIDI export", "stem download", "emotion-based generation"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["film scoring", "game soundtracks", "commercial music", "classical composition exploration", "background music for media"],
        "limitations": ["3 downloads/month on free", "no commercial use on free", "style limited compared to Suno for pop/electronic"],
        "verified_date": TODAY, "active": True,
    },

    # ── TRANSLATION AI (was 4, target 7) ─────────────────────────────────

    {
        "id": "deepl-write",
        "name": "DeepL Write",
        "description": "AI writing assistant from DeepL that improves phrasing, grammar, and style in English and German. Suggests multiple rephrasings and tone adjustments — different from DeepL Translate.",
        "category_id": "translation-ai",
        "website_url": "https://www.deepl.com/write",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: basic writing improvements, limited text length; Pro included with DeepL Pro subscription",
            api="No separate public API (part of DeepL API)",
            commercial=True,
        ),
        "capabilities": ["text improvement", "grammar correction", "style suggestions", "tone adjustment", "rephrasing", "English and German only"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["professional writing improvement", "business email refinement", "academic writing polish", "non-native English/German writing"],
        "limitations": ["English and German only", "writing assistant not translator", "advanced features need DeepL Pro"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "modernmt",
        "name": "ModernMT",
        "description": "Adaptive machine translation API that learns from human corrections over time. Used by professional translators and agencies. Context-aware translation that improves with feedback.",
        "category_id": "translation-ai",
        "website_url": "https://www.modernmt.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="200,000 characters per month on free tier",
            features="Free: 200k chars/month via API; Pay-as-you-go after free quota",
            api="REST API — free tier 200k chars/month",
            commercial=True,
        ),
        "capabilities": ["adaptive machine translation", "context-aware translation", "human correction learning", "50+ language pairs", "glossary support", "batch translation"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["professional translation workflows", "CAT tool integration", "adaptive enterprise translation", "content localisation with correction learning"],
        "limitations": ["API-focused (no clean web UI)", "adaptive features require correction data", "best for professional translator workflows"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "argos-translate",
        "name": "Argos Translate",
        "description": "Open-source offline machine translation library. Runs entirely locally — no internet connection required, no data sent to servers. Supports 30+ languages. Privacy-first alternative to cloud translation.",
        "category_id": "translation-ai",
        "website_url": "https://www.argosopentech.com",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited — runs fully offline",
            features="Completely free and open source; requires local installation; no API calls, no usage limits",
            api="Python library — local use only",
            commercial=True,
        ),
        "capabilities": ["offline translation", "30+ language pairs", "privacy-preserving translation", "batch translation", "Python integration", "no internet required"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["privacy-sensitive translation", "offline environments", "open-source projects", "developer local translation", "regulated industries requiring on-premise"],
        "limitations": ["lower quality than DeepL/Google for nuanced text", "requires local installation", "no web interface by default"],
        "verified_date": TODAY, "active": True,
    },

    # ── AI AGENTS (was 7, target 10) ─────────────────────────────────────

    {
        "id": "agentgpt",
        "name": "AgentGPT",
        "description": "Browser-based autonomous AI agent that plans and executes multi-step tasks without installation. Built on GPT-4, it creates and runs agent chains in your browser — no local setup needed.",
        "category_id": "ai-agents",
        "website_url": "https://agentgpt.reworkd.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            features="Free: limited agent runs per day; Pro $40/month: unlimited runs, GPT-4, custom model selection",
            api="Open source — self-hostable",
            commercial=True,
        ),
        "capabilities": ["autonomous task execution", "multi-step planning", "web browsing", "code execution", "no-install browser-based agents", "open source"],
        "input_types": ["text"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["automated research", "task chaining without local setup", "prototyping agent workflows", "open-source agent experimentation"],
        "limitations": ["limited free runs", "less stable than local agent frameworks", "Pro $40/month for production use"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "activepieces",
        "name": "Activepieces",
        "description": "Open-source no-code automation platform (Zapier alternative). Self-hostable for complete data privacy. Supports 200+ integrations and AI agent flows. Free cloud tier available.",
        "category_id": "ai-agents",
        "website_url": "https://www.activepieces.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(
            monthly="1,000 tasks/month on cloud free plan",
            features="Free cloud: 1,000 tasks/month, 5 active flows; Self-hosted: completely unlimited and free",
            api="Full REST API",
            commercial=True,
        ),
        "capabilities": ["no-code automation", "200+ integrations", "AI agent flows", "webhook support", "self-hosting", "open source", "data transformation"],
        "input_types": ["text", "code"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["privacy-first automation", "self-hosted workflows", "Zapier replacement", "business process automation", "AI-powered workflows"],
        "limitations": ["1,000 tasks/month on cloud free", "self-hosting requires technical setup", "smaller integration library than Zapier"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "fixie-ai",
        "name": "Flowise",
        "description": "Open-source visual tool for building LLM-powered applications and AI agent flows using a drag-and-drop interface. Built on LangChain. Self-hostable and completely free.",
        "category_id": "ai-agents",
        "website_url": "https://flowiseai.com",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(
            gen_limit="Unlimited on self-hosted; Flowise Cloud also available",
            features="Open source — completely free self-hosted; Cloud plans available for managed hosting",
            api="REST API + embedded chat",
            commercial=True,
        ),
        "capabilities": ["visual LLM app builder", "AI agent creation", "RAG pipelines", "chatbot building", "tool integration", "drag-and-drop workflow", "LangChain-based"],
        "input_types": ["text", "code", "document"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["building RAG chatbots", "visual AI workflow creation", "LLM app prototyping", "customer support bots", "internal knowledge assistants"],
        "limitations": ["requires technical setup for self-hosting", "needs own LLM API keys", "rapidly evolving API"],
        "verified_date": TODAY, "active": True,
    },
]


def seed():
    db = get_db()
    col = db.collection("tools")
    for tool in TOOLS:
        col.document(tool["id"]).set(tool)
        print(f"  ✓ {tool['name']} ({tool['category_id']}) — {tool['pricing_type']}")
    print(f"\nSeeded {len(TOOLS)} new tools.")


if __name__ == "__main__":
    seed()
