"""
Seed script: writes AI tool records to Firestore covering all 13 categories.
Idempotent — uses tool ID as document ID.

Usage:
    cd backend
    python -m scripts.seed_tools
"""

import os, sys, datetime
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv
load_dotenv()

from app.db.firestore_client import get_db

TODAY = datetime.date.today().isoformat()

def ftd(credits=None, gen_limit=None, daily=None, monthly=None, watermark=False,
        watermark_details=None, features=None, api=None, commercial=True):
    return {
        "credits": credits, "generation_limit": gen_limit,
        "daily_limit": daily, "monthly_limit": monthly,
        "has_watermark": watermark, "watermark_details": watermark_details,
        "feature_restrictions": features, "api_restrictions": api,
        "commercial_use_allowed": commercial,
    }

TOOLS = [
    # ── CHAT & CONVERSATIONAL AI ─────────────────────────────────────────────
    {
        "id": "chatgpt",
        "name": "ChatGPT",
        "description": "OpenAI's conversational AI assistant capable of answering questions, writing, coding, and reasoning across a wide range of topics.",
        "category_id": "chat-ai",
        "website_url": "https://chat.openai.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="Limited GPT-4o messages on free tier", features="GPT-4o access limited; no image generation in free tier", api="API requires paid plan"),
        "capabilities": ["text generation", "question answering", "code generation", "summarisation", "translation", "image understanding"],
        "input_types": ["text", "image"],
        "output_types": ["text", "image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["writing assistance", "coding help", "research", "brainstorming", "customer support"],
        "limitations": ["knowledge cutoff", "can hallucinate facts", "free tier usage limits"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "claude",
        "name": "Claude",
        "description": "Anthropic's AI assistant focused on safety and helpfulness. Excellent at long-document analysis, nuanced reasoning, and coding.",
        "category_id": "chat-ai",
        "website_url": "https://claude.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="Limited messages per day on free tier", features="Claude 3.5 Sonnet limited on free; no API access", api="API requires paid plan"),
        "capabilities": ["text generation", "long document analysis", "question answering", "code generation", "summarisation"],
        "input_types": ["text", "document", "image"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["document analysis", "long-form writing", "nuanced reasoning", "research", "coding"],
        "limitations": ["knowledge cutoff", "no image generation", "free tier message limits"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "gemini",
        "name": "Gemini",
        "description": "Google's multimodal AI assistant available via web, mobile, and API. Supports text, images, audio, and integrates with Google Workspace.",
        "category_id": "chat-ai",
        "website_url": "https://gemini.google.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="Limited requests on Gemini Pro in free tier", features="Gemini Advanced requires Google One subscription", api="API free tier: 15 req/min, 1M tokens/day"),
        "capabilities": ["text generation", "image understanding", "code generation", "multimodal reasoning", "translation"],
        "input_types": ["text", "image", "audio", "video"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["multimodal Q&A", "document analysis", "coding", "research", "Google Workspace integration"],
        "limitations": ["Gemini Advanced requires paid plan", "some features region-locked"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "meta-ai",
        "name": "Meta AI",
        "description": "Meta's free AI assistant powered by Llama, available on WhatsApp, Instagram, Messenger, and the web.",
        "category_id": "chat-ai",
        "website_url": "https://www.meta.ai",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(features="Available across Meta platforms", commercial=False),
        "capabilities": ["text generation", "question answering", "image generation", "summarisation"],
        "input_types": ["text", "image"],
        "output_types": ["text", "image"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["quick Q&A", "social media assistance", "casual conversation", "image generation"],
        "limitations": ["no API access", "integrated into Meta platforms only", "limited document handling"],
        "verified_date": TODAY, "active": True,
    },

    # ── WRITING AI ───────────────────────────────────────────────────────────
    {
        "id": "grammarly",
        "name": "Grammarly",
        "description": "AI writing assistant that checks grammar, spelling, style, and tone. Integrates with browsers, Word, and Google Docs.",
        "category_id": "writing-ai",
        "website_url": "https://www.grammarly.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(features="Free tier: basic grammar/spelling only; no tone, clarity, or AI rewrites", api="No public API"),
        "capabilities": ["grammar checking", "spell checking", "style suggestions", "tone detection", "AI rewriting", "plagiarism detection"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["email writing", "academic writing", "professional documents", "social media posts"],
        "limitations": ["free tier very limited", "plagiarism check requires paid", "best features behind paywall"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "jasper",
        "name": "Jasper",
        "description": "AI content platform for marketing teams. Generates blog posts, ads, emails, and social content with brand voice consistency.",
        "category_id": "writing-ai",
        "website_url": "https://www.jasper.ai",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(credits="7-day free trial", gen_limit="Limited words during trial", features="Full features during trial; credit card required"),
        "capabilities": ["blog writing", "ad copy", "email writing", "social media content", "brand voice", "SEO content"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["marketing copy", "blog articles", "email campaigns", "product descriptions", "social media"],
        "limitations": ["expensive after trial", "requires credit card for trial", "output needs human review"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "copy-ai",
        "name": "Copy.ai",
        "description": "AI writing tool for generating marketing copy, blog posts, and social media content. Has a generous free tier.",
        "category_id": "writing-ai",
        "website_url": "https://www.copy.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="2,000 words per month on free plan", features="Limited to 1 user and 1 workspace on free"),
        "capabilities": ["marketing copy", "blog writing", "email writing", "social media content", "product descriptions"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["short-form copy", "social media captions", "email subject lines", "product listings"],
        "limitations": ["2000 word/month free limit", "1 workspace on free", "output can be generic"],
        "verified_date": TODAY, "active": True,
    },

    # ── RESEARCH AI ──────────────────────────────────────────────────────────
    {
        "id": "perplexity",
        "name": "Perplexity AI",
        "description": "AI-powered search engine that answers questions with real-time web sources and citations. Combines search and language models.",
        "category_id": "research-ai",
        "website_url": "https://www.perplexity.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="Limited Pro searches per day", features="Free uses standard model; Pro uses GPT-4/Claude", api="API requires paid plan"),
        "capabilities": ["web search", "question answering", "source citation", "research synthesis", "follow-up questions"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["research", "fact checking", "current events", "quick answers with sources", "academic research"],
        "limitations": ["free tier limited Pro searches", "can hallucinate despite citations"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "consensus",
        "name": "Consensus",
        "description": "AI research tool that searches and synthesises findings from peer-reviewed scientific papers, with citation support.",
        "category_id": "research-ai",
        "website_url": "https://consensus.app",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="20 searches per month on free tier", features="Premium features: unlimited searches, GPT-4 summaries, export"),
        "capabilities": ["scientific paper search", "research synthesis", "citation extraction", "consensus summarisation"],
        "input_types": ["text"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["academic research", "literature reviews", "evidence-based questions", "scientific fact checking"],
        "limitations": ["only covers published research", "20 free searches/month", "no social science coverage"],
        "verified_date": TODAY, "active": True,
    },

    # ── IMAGE GENERATION ─────────────────────────────────────────────────────
    {
        "id": "midjourney",
        "name": "Midjourney",
        "description": "A leading AI image generation tool creating high-quality artistic images from text prompts via Discord or web.",
        "category_id": "image-generation",
        "website_url": "https://www.midjourney.com",
        "pricing_type": "Paid Only",
        "free_availability": False,
        "free_tier_details": None,
        "capabilities": ["image generation", "image variation", "upscaling", "style transfer", "inpainting"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["artistic image creation", "concept art", "marketing visuals", "creative exploration"],
        "limitations": ["no free tier", "no public API", "commercial use requires higher tier"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "stable-diffusion-xl",
        "name": "Stable Diffusion XL",
        "description": "Open-source text-to-image model by Stability AI. Run locally for free or use via hosted APIs.",
        "category_id": "image-generation",
        "website_url": "https://stability.ai/stable-image",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Unlimited when self-hosted", features="Requires local GPU for self-hosting"),
        "capabilities": ["image generation", "inpainting", "outpainting", "image-to-image", "fine-tuning"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["open-source image generation", "local deployment", "commercial projects", "fine-tuning"],
        "limitations": ["requires powerful GPU for local use", "setup complexity"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "dalle3",
        "name": "DALL-E 3",
        "description": "OpenAI's image generation model integrated into ChatGPT. Creates highly accurate images from detailed text prompts.",
        "category_id": "image-generation",
        "website_url": "https://openai.com/dall-e-3",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="Limited generations on ChatGPT free tier", features="Available via ChatGPT free tier with daily limits", api="API requires paid OpenAI account"),
        "capabilities": ["text-to-image", "image editing", "style consistency", "detailed prompt following"],
        "input_types": ["text"],
        "output_types": ["image"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["illustration", "concept visualization", "marketing assets", "creative projects"],
        "limitations": ["limited free generations", "no outpainting in API", "usage policy restrictions"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "adobe-firefly",
        "name": "Adobe Firefly",
        "description": "Adobe's generative AI for images and text effects, trained on licensed content for commercial safety. Integrated into Creative Cloud.",
        "category_id": "image-generation",
        "website_url": "https://firefly.adobe.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="25 generative credits/month on free plan", features="Watermark on free tier; limited generations"),
        "capabilities": ["text-to-image", "generative fill", "text effects", "style reference", "recolor"],
        "input_types": ["text", "image"],
        "output_types": ["image"],
        "watermark_info": "Free tier images include Adobe Firefly watermark",
        "api_available": True,
        "best_use_cases": ["commercial design", "photo editing", "marketing assets", "Creative Cloud workflows"],
        "limitations": ["25 free credits/month", "watermark on free", "best with Adobe CC subscription"],
        "verified_date": TODAY, "active": True,
    },

    # ── VIDEO GENERATION ─────────────────────────────────────────────────────
    {
        "id": "runway-ml",
        "name": "Runway",
        "description": "Professional AI video generation and editing platform for text-to-video, image-to-video, and creative video tools.",
        "category_id": "video-generation",
        "website_url": "https://runwayml.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(credits="125 credits on signup", watermark=True, watermark_details="Free tier videos include Runway watermark", features="Limited resolution and duration on free tier", api="API requires paid plan", commercial=False),
        "capabilities": ["text-to-video", "image-to-video", "video editing", "background removal", "motion tracking"],
        "input_types": ["text", "image", "video"],
        "output_types": ["video"],
        "watermark_info": "Free tier adds Runway watermark to generated videos",
        "api_available": True,
        "best_use_cases": ["short film production", "marketing videos", "social media content", "creative video"],
        "limitations": ["free tier: watermark, limited credits, no commercial use"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "pika",
        "name": "Pika",
        "description": "AI video generation tool that creates and edits videos from text prompts or images. Known for creative style controls.",
        "category_id": "video-generation",
        "website_url": "https://pika.art",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="150 credits/month on free tier", watermark=True, watermark_details="Free tier videos have Pika watermark", commercial=False),
        "capabilities": ["text-to-video", "image-to-video", "video editing", "style modification"],
        "input_types": ["text", "image"],
        "output_types": ["video"],
        "watermark_info": "Free tier videos include Pika watermark",
        "api_available": False,
        "best_use_cases": ["short creative videos", "social content", "concept visualization", "animated clips"],
        "limitations": ["watermark on free", "limited duration", "no commercial use on free"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "sora",
        "name": "Sora",
        "description": "OpenAI's text-to-video model that generates realistic, high-quality videos up to 60 seconds from text descriptions.",
        "category_id": "video-generation",
        "website_url": "https://sora.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="Limited videos on free tier with watermark", watermark=True, watermark_details="Free tier videos include Sora watermark", commercial=False),
        "capabilities": ["text-to-video", "image-to-video", "video extension", "video remixing"],
        "input_types": ["text", "image"],
        "output_types": ["video"],
        "watermark_info": "Free tier includes Sora watermark",
        "api_available": False,
        "best_use_cases": ["cinematic video creation", "storytelling", "concept visualization", "creative exploration"],
        "limitations": ["limited free tier", "no API", "content policy restrictions"],
        "verified_date": TODAY, "active": True,
    },

    # ── VOICE & AUDIO ────────────────────────────────────────────────────────
    {
        "id": "elevenlabs",
        "name": "ElevenLabs",
        "description": "AI voice synthesis platform with highly realistic text-to-speech and voice cloning in 30+ languages.",
        "category_id": "voice-audio",
        "website_url": "https://elevenlabs.io",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="10,000 characters/month", features="Limited to 3 custom voices; lower quality downloads", api="API on free tier with limits", commercial=False),
        "capabilities": ["text-to-speech", "voice cloning", "voice design", "speech-to-speech", "dubbing"],
        "input_types": ["text", "audio"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["voiceovers", "audiobook narration", "podcast production", "accessibility", "dubbing"],
        "limitations": ["free tier: 10k chars/month, no commercial use"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "whisper",
        "name": "OpenAI Whisper",
        "description": "Open-source speech recognition model by OpenAI. Transcribes and translates audio in 90+ languages with high accuracy.",
        "category_id": "voice-audio",
        "website_url": "https://openai.com/research/whisper",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Unlimited when self-hosted", features="Requires local compute for self-hosting"),
        "capabilities": ["speech-to-text", "audio transcription", "language translation", "speaker identification"],
        "input_types": ["audio"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["meeting transcription", "podcast transcription", "subtitles", "multilingual transcription"],
        "limitations": ["requires compute for local use", "real-time transcription needs optimisation"],
        "verified_date": TODAY, "active": True,
    },

    # ── MUSIC GENERATION ─────────────────────────────────────────────────────
    {
        "id": "suno",
        "name": "Suno",
        "description": "AI music generation platform that creates full songs with vocals and instrumentation from text prompts.",
        "category_id": "music-generation",
        "website_url": "https://suno.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="50 credits/day (~10 songs)", gen_limit="~10 songs per day", commercial=False),
        "capabilities": ["music generation", "song creation", "lyric generation", "instrumental generation"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["background music", "song demos", "creative exploration", "content soundtracks"],
        "limitations": ["free tier: no commercial use", "limited musical structure control", "no public API"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "udio",
        "name": "Udio",
        "description": "AI music generator that creates high-quality songs from text descriptions. Strong at matching style and genre from prompts.",
        "category_id": "music-generation",
        "website_url": "https://www.udio.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="1,200 credits/month free (~400 songs)", commercial=False),
        "capabilities": ["music generation", "song creation", "style matching", "instrumental generation", "lyrics"],
        "input_types": ["text"],
        "output_types": ["audio"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["music creation", "genre exploration", "soundtrack creation", "demo tracks"],
        "limitations": ["no commercial use on free", "no public API", "limited control over structure"],
        "verified_date": TODAY, "active": True,
    },

    # ── CODING AI ────────────────────────────────────────────────────────────
    {
        "id": "github-copilot",
        "name": "GitHub Copilot",
        "description": "AI code completion and chat assistant integrated into VS Code, JetBrains, and other editors. Powered by OpenAI Codex.",
        "category_id": "coding-ai",
        "website_url": "https://github.com/features/copilot",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="2,000 completions and 50 chat messages/month on free tier", features="Free tier has monthly limits; advanced models on paid"),
        "capabilities": ["code completion", "code generation", "code explanation", "code review", "test generation"],
        "input_types": ["code", "text"],
        "output_types": ["code", "text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["IDE code completion", "boilerplate generation", "explaining code", "test generation"],
        "limitations": ["requires GitHub account", "free tier monthly limits", "may suggest insecure code"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "cursor",
        "name": "Cursor",
        "description": "AI-first code editor (VS Code fork) with deep AI integration for generating, editing, and chatting about entire codebases.",
        "category_id": "coding-ai",
        "website_url": "https://cursor.sh",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="Limited fast requests/month on free tier", features="Free tier has limited fast AI requests"),
        "capabilities": ["code generation", "codebase chat", "code editing", "bug fixing", "refactoring"],
        "input_types": ["code", "text"],
        "output_types": ["code", "text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["full-codebase AI editing", "refactoring", "feature development", "debugging"],
        "limitations": ["free tier limited fast requests", "large codebases hit context limits"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "codeium",
        "name": "Codeium",
        "description": "Free AI code completion and chat tool supporting 70+ languages and 40+ editors. Strong free tier with no usage limits.",
        "category_id": "coding-ai",
        "website_url": "https://codeium.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Unlimited completions on free tier for individuals", features="Teams and enterprise features require paid"),
        "capabilities": ["code completion", "code generation", "code explanation", "chat", "search"],
        "input_types": ["code", "text"],
        "output_types": ["code", "text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["code completion", "learning new languages", "boilerplate generation", "multi-language projects"],
        "limitations": ["team features require paid", "codebase indexing limited on free"],
        "verified_date": TODAY, "active": True,
    },

    # ── DESIGN AI ────────────────────────────────────────────────────────────
    {
        "id": "canva-ai",
        "name": "Canva AI",
        "description": "Canva's suite of AI design tools including Magic Studio, Magic Write, and AI image generation built into the Canva platform.",
        "category_id": "design-ai",
        "website_url": "https://www.canva.com/ai-image-generator",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="50 Magic Studio credits/month on free", features="Advanced AI features require Canva Pro"),
        "capabilities": ["AI image generation", "background removal", "magic resize", "text-to-design", "AI writing"],
        "input_types": ["text", "image"],
        "output_types": ["image", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["social media graphics", "presentations", "marketing materials", "quick designs"],
        "limitations": ["50 free AI credits/month", "advanced features require Pro", "limited design customization"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "uizard",
        "name": "Uizard",
        "description": "AI-powered UI/UX design tool that converts hand-drawn sketches or text prompts into wireframes and app mockups.",
        "category_id": "design-ai",
        "website_url": "https://uizard.io",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(features="Free: 3 projects, 2 screens/project; no AI features", api="No public API"),
        "capabilities": ["wireframing", "UI mockup generation", "sketch-to-design", "AI design generation", "prototyping"],
        "input_types": ["text", "image", "sketch"],
        "output_types": ["image", "prototype"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["rapid prototyping", "UI mockups", "app wireframing", "design ideation"],
        "limitations": ["free tier very limited", "AI features require paid", "not for production design"],
        "verified_date": TODAY, "active": True,
    },

    # ── PRODUCTIVITY AI ──────────────────────────────────────────────────────
    {
        "id": "notion-ai",
        "name": "Notion AI",
        "description": "AI writing and productivity assistant built into Notion for drafting, summarising, and organising content within workspaces.",
        "category_id": "productivity-ai",
        "website_url": "https://www.notion.com/product/ai",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(credits="20 free AI responses trial", gen_limit="20 AI actions then paid add-on required"),
        "capabilities": ["writing assistance", "summarisation", "action item extraction", "translation", "brainstorming"],
        "input_types": ["text", "document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["meeting notes summarisation", "document drafting", "knowledge base management"],
        "limitations": ["requires Notion workspace", "AI is paid add-on after trial"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "otter-ai",
        "name": "Otter.ai",
        "description": "AI meeting assistant that transcribes, summarises, and captures action items from meetings in real time.",
        "category_id": "productivity-ai",
        "website_url": "https://otter.ai",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="300 transcription minutes/month on free tier", features="Free: 3 meeting imports, no exports to other apps"),
        "capabilities": ["meeting transcription", "meeting summarisation", "action item extraction", "speaker identification"],
        "input_types": ["audio", "video"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["meeting notes", "interview transcription", "lecture notes", "podcast transcription"],
        "limitations": ["300 min/month free", "limited integrations on free", "accuracy varies with accents"],
        "verified_date": TODAY, "active": True,
    },

    # ── DOCUMENT AI ──────────────────────────────────────────────────────────
    {
        "id": "chatpdf",
        "name": "ChatPDF",
        "description": "AI tool that lets you chat with any PDF document — ask questions, get summaries, and extract information from PDFs.",
        "category_id": "document-ai",
        "website_url": "https://www.chatpdf.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(daily="2 PDFs/day, 3 questions/PDF on free tier", features="Free tier: max 120 pages per PDF, 10MB limit"),
        "capabilities": ["PDF Q&A", "document summarisation", "information extraction", "document chat"],
        "input_types": ["document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["reading research papers", "legal document review", "textbook Q&A", "report summarisation"],
        "limitations": ["2 PDFs/day free", "120 page limit", "no API access"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "adobe-acrobat-ai",
        "name": "Adobe Acrobat AI Assistant",
        "description": "Adobe's AI assistant for PDFs that generates summaries, answers questions about document content, and identifies key insights.",
        "category_id": "document-ai",
        "website_url": "https://www.adobe.com/acrobat/generative-ai-pdf.html",
        "pricing_type": "Free Trial",
        "free_availability": True,
        "free_tier_details": ftd(credits="Free trial available with Acrobat subscription trial", features="Full AI features only in Acrobat paid plans"),
        "capabilities": ["PDF summarisation", "document Q&A", "key insight extraction", "document comparison"],
        "input_types": ["document"],
        "output_types": ["text"],
        "watermark_info": None,
        "api_available": False,
        "best_use_cases": ["contract review", "research paper analysis", "report summarisation", "legal documents"],
        "limitations": ["requires Acrobat subscription for full access", "limited document size"],
        "verified_date": TODAY, "active": True,
    },

    # ── TRANSLATION AI ───────────────────────────────────────────────────────
    {
        "id": "deepl",
        "name": "DeepL",
        "description": "High-accuracy AI translation in 30+ languages, known for natural-sounding output that rivals human translators.",
        "category_id": "translation-ai",
        "website_url": "https://www.deepl.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(monthly="500,000 characters/month via API free tier", features="Free web translator unlimited; API capped", api="API free tier: 500k chars/month"),
        "capabilities": ["text translation", "document translation", "glossary support", "formality control"],
        "input_types": ["text", "document"],
        "output_types": ["text", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["professional document translation", "multilingual content", "website localisation"],
        "limitations": ["30+ languages (fewer than Google Translate)", "API free tier capped"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "google-translate",
        "name": "Google Translate",
        "description": "Google's free translation service supporting 130+ languages with text, image, voice, and document translation.",
        "category_id": "translation-ai",
        "website_url": "https://translate.google.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Unlimited on web; API has free quota", monthly="500,000 chars/month API free tier"),
        "capabilities": ["text translation", "image translation", "voice translation", "document translation", "website translation"],
        "input_types": ["text", "image", "audio", "document"],
        "output_types": ["text", "audio"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["quick translations", "travel", "real-time conversation", "website localisation"],
        "limitations": ["less accurate than DeepL for formal text", "API free quota limited"],
        "verified_date": TODAY, "active": True,
    },

    # ── AI AGENTS ────────────────────────────────────────────────────────────
    {
        "id": "autogpt",
        "name": "AutoGPT",
        "description": "Open-source autonomous AI agent that uses GPT-4 to complete multi-step tasks with web browsing, file management, and code execution.",
        "category_id": "ai-agents",
        "website_url": "https://agpt.co",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Unlimited (requires own OpenAI API key)", features="Requires own OpenAI API key with associated costs"),
        "capabilities": ["autonomous task execution", "web browsing", "file management", "code execution", "memory"],
        "input_types": ["text"],
        "output_types": ["text", "code", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["automated research", "multi-step task automation", "data collection", "report generation"],
        "limitations": ["requires own OpenAI API key (costs money)", "unstable for complex tasks", "technical setup required"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "crew-ai",
        "name": "CrewAI",
        "description": "Framework for orchestrating multiple AI agents that work together as a crew to complete complex tasks with role-based specialisation.",
        "category_id": "ai-agents",
        "website_url": "https://www.crewai.com",
        "pricing_type": "Freemium",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Open source framework is free to use", features="CrewAI+ cloud platform has paid tiers; local use always free"),
        "capabilities": ["multi-agent orchestration", "role-based agents", "task delegation", "tool use", "autonomous workflows"],
        "input_types": ["text", "code"],
        "output_types": ["text", "code", "document"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["complex workflow automation", "research pipelines", "content generation pipelines", "data analysis"],
        "limitations": ["requires programming knowledge", "needs LLM API keys", "complex to debug"],
        "verified_date": TODAY, "active": True,
    },
    {
        "id": "langchain",
        "name": "LangChain",
        "description": "Open-source framework for building applications with large language models. Connects LLMs to tools, data, and memory.",
        "category_id": "ai-agents",
        "website_url": "https://www.langchain.com",
        "pricing_type": "Completely Free",
        "free_availability": True,
        "free_tier_details": ftd(gen_limit="Framework is completely free and open source", features="LangSmith cloud platform has paid tiers"),
        "capabilities": ["LLM chaining", "agent creation", "RAG", "tool integration", "memory management", "document Q&A"],
        "input_types": ["text", "document", "code"],
        "output_types": ["text", "code"],
        "watermark_info": None,
        "api_available": True,
        "best_use_cases": ["building LLM apps", "RAG applications", "chatbots", "document Q&A systems", "AI agents"],
        "limitations": ["requires programming knowledge", "rapidly changing API", "needs LLM API keys"],
        "verified_date": TODAY, "active": True,
    },
]


def seed():
    db = get_db()
    col = db.collection("tools")
    for tool in TOOLS:
        doc_id = tool["id"]
        col.document(doc_id).set(tool)
        print(f"  \u2713 {tool['name']} ({tool['category_id']}) \u2014 {tool['pricing_type']}")
    print(f"\nSeeded {len(TOOLS)} tools across all categories.")


if __name__ == "__main__":
    seed()
