"""
Router: /finder
Task-based AI Finder — given a natural language task description,
return ranked tool recommendations with reasoning.

Ranking: pure rule-based scoring (no external dependency).
Reasoning text: generated by Gemini 1.5 Flash when GEMINI_API_KEY is set.
Fallback: if Gemini is unavailable or errors, rule-based reasoning is used silently.
"""

from __future__ import annotations

import os
import logging
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field
from app.db.tools_db import fetch_tools

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/finder", tags=["finder"])


# ---------------------------------------------------------------------------
# Request / Response models
# ---------------------------------------------------------------------------

class FinderRequest(BaseModel):
    task: str = Field(..., min_length=5, max_length=500)


class ToolRecommendation(BaseModel):
    tool: dict
    score: int
    reasoning: str


class FinderResponse(BaseModel):
    task: str
    recommendations: list[ToolRecommendation]
    total: int
    reasoning_source: str  # "gemini" | "rule-based"


# ---------------------------------------------------------------------------
# Category hint map  (task keyword → likely categories)
# ---------------------------------------------------------------------------

_TASK_CATEGORY_HINTS: dict[str, list[str]] = {
    "video": ["video-generation"],
    "film": ["video-generation"],
    "clip": ["video-generation"],
    "animate": ["video-generation"],
    "image": ["image-generation"],
    "photo": ["image-generation"],
    "picture": ["image-generation"],
    "illustration": ["image-generation"],
    "logo": ["image-generation", "design-ai"],
    "design": ["design-ai", "image-generation"],
    "ui": ["design-ai", "coding-ai"],
    "ux": ["design-ai"],
    "wireframe": ["design-ai"],
    "mockup": ["design-ai"],
    "code": ["coding-ai"],
    "coding": ["coding-ai"],
    "program": ["coding-ai"],
    "develop": ["coding-ai"],
    "build": ["coding-ai"],
    "app": ["coding-ai"],
    "website": ["coding-ai", "design-ai"],
    "write": ["writing-ai", "chat-ai"],
    "blog": ["writing-ai"],
    "article": ["writing-ai"],
    "essay": ["writing-ai"],
    "copy": ["writing-ai"],
    "email": ["writing-ai", "productivity-ai"],
    "music": ["music-generation"],
    "song": ["music-generation"],
    "soundtrack": ["music-generation"],
    "beat": ["music-generation"],
    "voice": ["voice-audio"],
    "speech": ["voice-audio"],
    "narrate": ["voice-audio"],
    "tts": ["voice-audio"],
    "podcast": ["voice-audio", "music-generation"],
    "transcribe": ["voice-audio", "document-ai"],
    "translate": ["translation-ai"],
    "language": ["translation-ai", "chat-ai"],
    "research": ["research-ai", "chat-ai"],
    "paper": ["research-ai", "document-ai"],
    "summarise": ["document-ai", "research-ai", "productivity-ai"],
    "summarize": ["document-ai", "research-ai", "productivity-ai"],
    "pdf": ["document-ai"],
    "document": ["document-ai"],
    "meeting": ["productivity-ai"],
    "schedule": ["productivity-ai"],
    "automate": ["ai-agents", "productivity-ai"],
    "agent": ["ai-agents"],
    "workflow": ["ai-agents", "productivity-ai"],
    "chat": ["chat-ai"],
    "question": ["chat-ai", "research-ai"],
    "answer": ["chat-ai", "research-ai"],
    "llm": ["ai-api-providers"],
    "api": ["ai-api-providers"],
    "integrate": ["ai-api-providers", "ai-agents"],
    "sdk": ["ai-api-providers"],
    "token": ["ai-api-providers"],
    "inference": ["ai-api-providers"],
    "embed": ["ai-api-providers"],
    "embedding": ["ai-api-providers"],
    "rag": ["ai-api-providers", "research-ai"],
    "openai": ["ai-api-providers"],
    "anthropic": ["ai-api-providers"],
    "groq": ["ai-api-providers"],
    "mistral": ["ai-api-providers"],
}

_FREE_KEYWORDS = {"free", "freemium", "no cost", "without paying", "budget", "cheap", "affordable"}


def _detect_free_requirement(task: str) -> bool:
    t = task.lower()
    return any(kw in t for kw in _FREE_KEYWORDS)


def _detect_no_watermark(task: str) -> bool:
    t = task.lower()
    return "watermark" in t and ("no " in t or "without" in t)


def _detect_api_requirement(task: str) -> bool:
    t = task.lower()
    return "api" in t or "integrate" in t or "programmatically" in t


# ---------------------------------------------------------------------------
# Rule-based scoring
# ---------------------------------------------------------------------------

def _score_tools(
    tools: list[dict],
    task: str,
    hinted_categories: set[str],
    wants_free: bool,
    wants_no_watermark: bool,
    wants_api: bool,
) -> list[tuple[int, dict]]:
    task_words = task.lower().split()
    scored: list[tuple[int, dict]] = []

    for tool in tools:
        if not tool.get("active", False):
            continue
        score = 0

        # Category hint
        if tool.get("category_id") in hinted_categories:
            score += 200

        # Word-level field matching
        for word in task_words:
            if len(word) < 3:
                continue
            if word in tool.get("name", "").lower():
                score += 80
            if any(word in c.lower() for c in tool.get("capabilities", [])):
                score += 40
            if any(word in u.lower() for u in tool.get("best_use_cases", [])):
                score += 30
            if word in tool.get("description", "").lower():
                score += 10
            if word in tool.get("category_id", "").lower():
                score += 20

        # Free tier preference
        if wants_free:
            pt = tool.get("pricing_type", "")
            if pt == "Completely Free":
                score += 150
            elif pt in ("Freemium", "Free Trial") and tool.get("free_availability"):
                score += 80
            elif pt == "Paid Only":
                score -= 100

        # No watermark preference
        if wants_no_watermark:
            ftd = tool.get("free_tier_details") or {}
            hw = ftd.get("has_watermark") if isinstance(ftd, dict) else None
            if hw is False:
                score += 50
            elif hw is True:
                score -= 30

        # API preference
        if wants_api and tool.get("api_available"):
            score += 60

        if score > 0:
            scored.append((score, tool))

    scored.sort(key=lambda x: x[0], reverse=True)
    return scored[:6]


# ---------------------------------------------------------------------------
# Rule-based reasoning (fallback)
# ---------------------------------------------------------------------------

def _rule_reasoning(
    tool: dict,
    task: str,
    wants_free: bool,
    wants_no_watermark: bool,
    wants_api: bool,
) -> str:
    parts: list[str] = []
    task_words = set(task.lower().split())

    cat = tool.get("category_id", "").replace("-", " ")
    parts.append(f"Belongs to the {cat} category, which is relevant to your task.")

    if wants_free:
        pt = tool.get("pricing_type", "")
        if pt == "Completely Free":
            parts.append("Completely free — no payment ever required.")
        elif pt in ("Freemium", "Free Trial"):
            ftd = tool.get("free_tier_details") or {}
            note = ftd.get("daily_limit") or ftd.get("monthly_limit") or ftd.get("credits") if isinstance(ftd, dict) else None
            parts.append(f"Has a free tier{': ' + note if note else ''}.")

    if wants_no_watermark:
        ftd = tool.get("free_tier_details") or {}
        hw = ftd.get("has_watermark") if isinstance(ftd, dict) else None
        if hw is False:
            parts.append("Free tier does not add a watermark.")
        elif hw is True:
            parts.append("Free tier adds a watermark — paid plan removes it.")

    if wants_api and tool.get("api_available"):
        parts.append("Provides an API for programmatic integration.")

    caps = [c for c in tool.get("capabilities", []) if any(w in c.lower() for w in task_words)]
    if caps:
        parts.append(f"Relevant capabilities: {', '.join(caps[:3])}.")

    uses = [u for u in tool.get("best_use_cases", []) if any(w in u.lower() for w in task_words)]
    if uses:
        parts.append(f"Best for: {uses[0]}.")

    return " ".join(parts) or f"{tool.get('name')} is relevant to your task."


# ---------------------------------------------------------------------------
# Gemini-powered reasoning (primary, with fallback)
# ---------------------------------------------------------------------------

def _build_gemini_prompt(task: str, tools: list[dict]) -> str:
    tool_lines = []
    for i, tool in enumerate(tools, 1):
        ftd = tool.get("free_tier_details") or {}
        free_note = ""
        if isinstance(ftd, dict):
            for field in ("daily_limit", "monthly_limit", "credits"):
                if ftd.get(field):
                    free_note = f" (free limit: {ftd[field]})"
                    break
        tool_lines.append(
            f"{i}. {tool['name']} — {tool.get('pricing_type', '')} — "
            f"category: {tool.get('category_id', '').replace('-', ' ')}"
            f"{free_note} — "
            f"capabilities: {', '.join(tool.get('capabilities', [])[:4])}"
        )

    return f"""You are an AI tool recommendation assistant. A user described their task:

"{task}"

The following tools have been pre-selected as the best matches by a scoring algorithm:

{chr(10).join(tool_lines)}

For each tool, write ONE concise sentence (max 25 words) explaining exactly why it fits this specific task.
Be specific — mention the tool's relevant capability or free tier limit if it matters for this task.
Do NOT start with the tool name. Do NOT use generic phrases like "this tool is great".
Do NOT declare any tool the best.

Reply with ONLY a JSON array of strings, one per tool, in the same order. Example format:
["reason for tool 1", "reason for tool 2", "reason for tool 3"]"""


async def _gemini_reasoning(task: str, tools: list[dict]) -> list[str] | None:
    """
    Call Gemini 1.5 Flash to generate reasoning strings for each tool.
    Returns a list of strings (one per tool) or None if unavailable/failed.
    """
    api_key = os.getenv("GEMINI_API_KEY", "").strip()
    if not api_key:
        return None

    try:
        import google.generativeai as genai
        import json
        import asyncio

        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("gemini-1.5-flash")
        prompt = _build_gemini_prompt(task, tools)

        # Run synchronous Gemini call in a thread so we don't block the event loop
        loop = asyncio.get_event_loop()
        response = await asyncio.wait_for(
            loop.run_in_executor(None, lambda: model.generate_content(prompt)),
            timeout=8.0,  # 8-second timeout — fall back if slow
        )

        text = response.text.strip()

        # Strip markdown code fences if present
        if text.startswith("```"):
            text = text.split("```")[1]
            if text.startswith("json"):
                text = text[4:]
        text = text.strip()

        reasons = json.loads(text)
        if isinstance(reasons, list) and len(reasons) == len(tools):
            return [str(r).strip() for r in reasons]
        return None

    except Exception as exc:
        logger.warning("Gemini reasoning failed — using rule-based fallback. Error: %s", exc)
        return None


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.post("", response_model=FinderResponse)
async def find_tools_for_task(body: FinderRequest):
    """
    Given a natural language task description, return ranked tool recommendations.
    Ranking is rule-based. Reasoning is generated by Gemini 1.5 Flash when
    GEMINI_API_KEY is set; falls back to rule-based reasoning automatically.
    """
    task = body.task.strip()
    task_lower = task.lower()

    wants_free = _detect_free_requirement(task)
    wants_no_watermark = _detect_no_watermark(task)
    wants_api = _detect_api_requirement(task)

    # Collect category hints
    hinted_categories: set[str] = set()
    for keyword, cats in _TASK_CATEGORY_HINTS.items():
        if keyword in task_lower:
            hinted_categories.update(cats)

    # Fetch all active tools and score them
    all_tools, _ = fetch_tools(limit=500, offset=0)
    top_scored = _score_tools(all_tools, task, hinted_categories, wants_free, wants_no_watermark, wants_api)

    if not top_scored:
        return FinderResponse(task=task, recommendations=[], total=0, reasoning_source="rule-based")

    top_tools = [t for _, t in top_scored]

    # Try Gemini reasoning first, fall back to rule-based
    gemini_reasons = await _gemini_reasoning(task, top_tools)
    reasoning_source = "gemini" if gemini_reasons else "rule-based"

    recommendations = []
    for idx, (score, tool) in enumerate(top_scored):
        if gemini_reasons and idx < len(gemini_reasons):
            reasoning = gemini_reasons[idx]
        else:
            reasoning = _rule_reasoning(tool, task, wants_free, wants_no_watermark, wants_api)

        recommendations.append(
            ToolRecommendation(tool=tool, score=score, reasoning=reasoning)
        )

    return FinderResponse(
        task=task,
        recommendations=recommendations,
        total=len(recommendations),
        reasoning_source=reasoning_source,
    )
